// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: remes/remes/v1/node.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeType represents the type of node
type NodeType int32

const (
	// NODE_TYPE_UNSPECIFIED indicates an unspecified node type
	NodeType_NODE_TYPE_UNSPECIFIED NodeType = 0
	// NODE_TYPE_MINING indicates a mining node
	NodeType_NODE_TYPE_MINING NodeType = 1
	// NODE_TYPE_SERVING indicates a serving node
	NodeType_NODE_TYPE_SERVING NodeType = 2
	// NODE_TYPE_VALIDATOR indicates a validator node
	NodeType_NODE_TYPE_VALIDATOR NodeType = 3
	// NODE_TYPE_PROPOSER indicates a proposer node
	NodeType_NODE_TYPE_PROPOSER NodeType = 4
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "NODE_TYPE_UNSPECIFIED",
		1: "NODE_TYPE_MINING",
		2: "NODE_TYPE_SERVING",
		3: "NODE_TYPE_VALIDATOR",
		4: "NODE_TYPE_PROPOSER",
	}
	NodeType_value = map[string]int32{
		"NODE_TYPE_UNSPECIFIED": 0,
		"NODE_TYPE_MINING":      1,
		"NODE_TYPE_SERVING":     2,
		"NODE_TYPE_VALIDATOR":   3,
		"NODE_TYPE_PROPOSER":    4,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_remes_remes_v1_node_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_remes_remes_v1_node_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_remes_remes_v1_node_proto_rawDescGZIP(), []int{0}
}

// NodeStatus represents the status of a node
type NodeStatus int32

const (
	// NODE_STATUS_UNSPECIFIED indicates an unspecified status
	NodeStatus_NODE_STATUS_UNSPECIFIED NodeStatus = 0
	// NODE_STATUS_ACTIVE indicates an active node
	NodeStatus_NODE_STATUS_ACTIVE NodeStatus = 1
	// NODE_STATUS_INACTIVE indicates an inactive node
	NodeStatus_NODE_STATUS_INACTIVE NodeStatus = 2
	// NODE_STATUS_SLASHED indicates a slashed node
	NodeStatus_NODE_STATUS_SLASHED NodeStatus = 3
	// NODE_STATUS_SUSPENDED indicates a suspended node
	NodeStatus_NODE_STATUS_SUSPENDED NodeStatus = 4
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNSPECIFIED",
		1: "NODE_STATUS_ACTIVE",
		2: "NODE_STATUS_INACTIVE",
		3: "NODE_STATUS_SLASHED",
		4: "NODE_STATUS_SUSPENDED",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNSPECIFIED": 0,
		"NODE_STATUS_ACTIVE":      1,
		"NODE_STATUS_INACTIVE":    2,
		"NODE_STATUS_SLASHED":     3,
		"NODE_STATUS_SUSPENDED":   4,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_remes_remes_v1_node_proto_enumTypes[1].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_remes_remes_v1_node_proto_enumTypes[1]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_remes_remes_v1_node_proto_rawDescGZIP(), []int{1}
}

// ResourceSpec represents the resource specification for a node
type ResourceSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cpu_cores is the number of CPU cores
	CpuCores uint32 `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	// memory_gb is the memory in GB
	MemoryGb uint32 `protobuf:"varint,2,opt,name=memory_gb,json=memoryGb,proto3" json:"memory_gb,omitempty"`
	// gpu_count is the number of GPUs
	GpuCount uint32 `protobuf:"varint,3,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	// gpu_memory_gb is the GPU memory in GB
	GpuMemoryGb uint32 `protobuf:"varint,4,opt,name=gpu_memory_gb,json=gpuMemoryGb,proto3" json:"gpu_memory_gb,omitempty"`
	// storage_gb is the storage in GB
	StorageGb uint32 `protobuf:"varint,5,opt,name=storage_gb,json=storageGb,proto3" json:"storage_gb,omitempty"`
	// network_bandwidth_mbps is the network bandwidth in Mbps
	NetworkBandwidthMbps uint32 `protobuf:"varint,6,opt,name=network_bandwidth_mbps,json=networkBandwidthMbps,proto3" json:"network_bandwidth_mbps,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResourceSpec) Reset() {
	*x = ResourceSpec{}
	mi := &file_remes_remes_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSpec) ProtoMessage() {}

func (x *ResourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_remes_remes_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSpec.ProtoReflect.Descriptor instead.
func (*ResourceSpec) Descriptor() ([]byte, []int) {
	return file_remes_remes_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceSpec) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *ResourceSpec) GetMemoryGb() uint32 {
	if x != nil {
		return x.MemoryGb
	}
	return 0
}

func (x *ResourceSpec) GetGpuCount() uint32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *ResourceSpec) GetGpuMemoryGb() uint32 {
	if x != nil {
		return x.GpuMemoryGb
	}
	return 0
}

func (x *ResourceSpec) GetStorageGb() uint32 {
	if x != nil {
		return x.StorageGb
	}
	return 0
}

func (x *ResourceSpec) GetNetworkBandwidthMbps() uint32 {
	if x != nil {
		return x.NetworkBandwidthMbps
	}
	return 0
}

// ResourceQuota represents a resource quota for a specific role
type ResourceQuota struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role is the node role
	Role NodeType `protobuf:"varint,1,opt,name=role,proto3,enum=remes.remes.v1.NodeType" json:"role,omitempty"`
	// cpu_cores is the allocated CPU cores
	CpuCores uint32 `protobuf:"varint,2,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	// memory_gb is the allocated memory in GB
	MemoryGb uint32 `protobuf:"varint,3,opt,name=memory_gb,json=memoryGb,proto3" json:"memory_gb,omitempty"`
	// gpu_count is the allocated GPUs
	GpuCount uint32 `protobuf:"varint,4,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	// gpu_memory_gb is the allocated GPU memory in GB
	GpuMemoryGb   uint32 `protobuf:"varint,5,opt,name=gpu_memory_gb,json=gpuMemoryGb,proto3" json:"gpu_memory_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceQuota) Reset() {
	*x = ResourceQuota{}
	mi := &file_remes_remes_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceQuota) ProtoMessage() {}

func (x *ResourceQuota) ProtoReflect() protoreflect.Message {
	mi := &file_remes_remes_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceQuota.ProtoReflect.Descriptor instead.
func (*ResourceQuota) Descriptor() ([]byte, []int) {
	return file_remes_remes_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceQuota) GetRole() NodeType {
	if x != nil {
		return x.Role
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *ResourceQuota) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *ResourceQuota) GetMemoryGb() uint32 {
	if x != nil {
		return x.MemoryGb
	}
	return 0
}

func (x *ResourceQuota) GetGpuCount() uint32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *ResourceQuota) GetGpuMemoryGb() uint32 {
	if x != nil {
		return x.GpuMemoryGb
	}
	return 0
}

// NodeRegistration represents a registered node in the network
type NodeRegistration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_address is the address of the node
	NodeAddress string `protobuf:"bytes,1,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	// node_type is the primary node type
	NodeType NodeType `protobuf:"varint,2,opt,name=node_type,json=nodeType,proto3,enum=remes.remes.v1.NodeType" json:"node_type,omitempty"`
	// resources is the total resource specification
	Resources *ResourceSpec `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	// stake is the staked amount
	Stake string `protobuf:"bytes,4,opt,name=stake,proto3" json:"stake,omitempty"`
	// status is the node status
	Status NodeStatus `protobuf:"varint,5,opt,name=status,proto3,enum=remes.remes.v1.NodeStatus" json:"status,omitempty"`
	// roles is the list of roles this node can perform (multi-role support)
	Roles []NodeType `protobuf:"varint,6,rep,packed,name=roles,proto3,enum=remes.remes.v1.NodeType" json:"roles,omitempty"`
	// role_allocations maps roles to resource quotas
	RoleAllocations []*RoleAllocation `protobuf:"bytes,7,rep,name=role_allocations,json=roleAllocations,proto3" json:"role_allocations,omitempty"`
	// registered_at_height is the block height when registered
	RegisteredAtHeight int64 `protobuf:"varint,8,opt,name=registered_at_height,json=registeredAtHeight,proto3" json:"registered_at_height,omitempty"`
	// registered_at_time is the timestamp when registered
	RegisteredAtTime *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=registered_at_time,json=registeredAtTime,proto3" json:"registered_at_time,omitempty"`
	// resource_proof_ipfs_hash is the IPFS hash of the resource allocation proof
	ResourceProofIpfsHash string `protobuf:"bytes,10,opt,name=resource_proof_ipfs_hash,json=resourceProofIpfsHash,proto3" json:"resource_proof_ipfs_hash,omitempty"`
	// last_heartbeat_height is the last block height when node sent heartbeat
	LastHeartbeatHeight int64 `protobuf:"varint,11,opt,name=last_heartbeat_height,json=lastHeartbeatHeight,proto3" json:"last_heartbeat_height,omitempty"`
	// slashing_events is the number of slashing events
	SlashingEvents uint64 `protobuf:"varint,12,opt,name=slashing_events,json=slashingEvents,proto3" json:"slashing_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeRegistration) Reset() {
	*x = NodeRegistration{}
	mi := &file_remes_remes_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegistration) ProtoMessage() {}

func (x *NodeRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_remes_remes_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegistration.ProtoReflect.Descriptor instead.
func (*NodeRegistration) Descriptor() ([]byte, []int) {
	return file_remes_remes_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *NodeRegistration) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *NodeRegistration) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *NodeRegistration) GetResources() *ResourceSpec {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *NodeRegistration) GetStake() string {
	if x != nil {
		return x.Stake
	}
	return ""
}

func (x *NodeRegistration) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *NodeRegistration) GetRoles() []NodeType {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *NodeRegistration) GetRoleAllocations() []*RoleAllocation {
	if x != nil {
		return x.RoleAllocations
	}
	return nil
}

func (x *NodeRegistration) GetRegisteredAtHeight() int64 {
	if x != nil {
		return x.RegisteredAtHeight
	}
	return 0
}

func (x *NodeRegistration) GetRegisteredAtTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAtTime
	}
	return nil
}

func (x *NodeRegistration) GetResourceProofIpfsHash() string {
	if x != nil {
		return x.ResourceProofIpfsHash
	}
	return ""
}

func (x *NodeRegistration) GetLastHeartbeatHeight() int64 {
	if x != nil {
		return x.LastHeartbeatHeight
	}
	return 0
}

func (x *NodeRegistration) GetSlashingEvents() uint64 {
	if x != nil {
		return x.SlashingEvents
	}
	return 0
}

// RoleAllocation represents resource allocation for a specific role
type RoleAllocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role is the node role
	Role NodeType `protobuf:"varint,1,opt,name=role,proto3,enum=remes.remes.v1.NodeType" json:"role,omitempty"`
	// quota is the resource quota for this role
	Quota         *ResourceQuota `protobuf:"bytes,2,opt,name=quota,proto3" json:"quota,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAllocation) Reset() {
	*x = RoleAllocation{}
	mi := &file_remes_remes_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAllocation) ProtoMessage() {}

func (x *RoleAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_remes_remes_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAllocation.ProtoReflect.Descriptor instead.
func (*RoleAllocation) Descriptor() ([]byte, []int) {
	return file_remes_remes_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *RoleAllocation) GetRole() NodeType {
	if x != nil {
		return x.Role
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *RoleAllocation) GetQuota() *ResourceQuota {
	if x != nil {
		return x.Quota
	}
	return nil
}

var File_remes_remes_v1_node_proto protoreflect.FileDescriptor

const file_remes_remes_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x19remes/remes/v1/node.proto\x12\x0eremes.remes.v1\x1a\x11amino/amino.proto\x1a\x14gogoproto/gogo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x01\n" +
	"\fResourceSpec\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\rR\bcpuCores\x12\x1b\n" +
	"\tmemory_gb\x18\x02 \x01(\rR\bmemoryGb\x12\x1b\n" +
	"\tgpu_count\x18\x03 \x01(\rR\bgpuCount\x12\"\n" +
	"\rgpu_memory_gb\x18\x04 \x01(\rR\vgpuMemoryGb\x12\x1d\n" +
	"\n" +
	"storage_gb\x18\x05 \x01(\rR\tstorageGb\x124\n" +
	"\x16network_bandwidth_mbps\x18\x06 \x01(\rR\x14networkBandwidthMbps\"\xb8\x01\n" +
	"\rResourceQuota\x12,\n" +
	"\x04role\x18\x01 \x01(\x0e2\x18.remes.remes.v1.NodeTypeR\x04role\x12\x1b\n" +
	"\tcpu_cores\x18\x02 \x01(\rR\bcpuCores\x12\x1b\n" +
	"\tmemory_gb\x18\x03 \x01(\rR\bmemoryGb\x12\x1b\n" +
	"\tgpu_count\x18\x04 \x01(\rR\bgpuCount\x12\"\n" +
	"\rgpu_memory_gb\x18\x05 \x01(\rR\vgpuMemoryGb\"\x8f\x05\n" +
	"\x10NodeRegistration\x12!\n" +
	"\fnode_address\x18\x01 \x01(\tR\vnodeAddress\x125\n" +
	"\tnode_type\x18\x02 \x01(\x0e2\x18.remes.remes.v1.NodeTypeR\bnodeType\x12@\n" +
	"\tresources\x18\x03 \x01(\v2\x1c.remes.remes.v1.ResourceSpecB\x04\xc8\xde\x1f\x00R\tresources\x12\x14\n" +
	"\x05stake\x18\x04 \x01(\tR\x05stake\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.remes.remes.v1.NodeStatusR\x06status\x12.\n" +
	"\x05roles\x18\x06 \x03(\x0e2\x18.remes.remes.v1.NodeTypeR\x05roles\x12I\n" +
	"\x10role_allocations\x18\a \x03(\v2\x1e.remes.remes.v1.RoleAllocationR\x0froleAllocations\x120\n" +
	"\x14registered_at_height\x18\b \x01(\x03R\x12registeredAtHeight\x12R\n" +
	"\x12registered_at_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\x10registeredAtTime\x127\n" +
	"\x18resource_proof_ipfs_hash\x18\n" +
	" \x01(\tR\x15resourceProofIpfsHash\x122\n" +
	"\x15last_heartbeat_height\x18\v \x01(\x03R\x13lastHeartbeatHeight\x12'\n" +
	"\x0fslashing_events\x18\f \x01(\x04R\x0eslashingEvents\"y\n" +
	"\x0eRoleAllocation\x12,\n" +
	"\x04role\x18\x01 \x01(\x0e2\x18.remes.remes.v1.NodeTypeR\x04role\x129\n" +
	"\x05quota\x18\x02 \x01(\v2\x1d.remes.remes.v1.ResourceQuotaB\x04\xc8\xde\x1f\x00R\x05quota*\x89\x01\n" +
	"\bNodeType\x12\x19\n" +
	"\x15NODE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10NODE_TYPE_MINING\x10\x01\x12\x15\n" +
	"\x11NODE_TYPE_SERVING\x10\x02\x12\x17\n" +
	"\x13NODE_TYPE_VALIDATOR\x10\x03\x12\x16\n" +
	"\x12NODE_TYPE_PROPOSER\x10\x04\x1a\x04\x88\xa3\x1e\x00*\x95\x01\n" +
	"\n" +
	"NodeStatus\x12\x1b\n" +
	"\x17NODE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12NODE_STATUS_ACTIVE\x10\x01\x12\x18\n" +
	"\x14NODE_STATUS_INACTIVE\x10\x02\x12\x17\n" +
	"\x13NODE_STATUS_SLASHED\x10\x03\x12\x19\n" +
	"\x15NODE_STATUS_SUSPENDED\x10\x04\x1a\x04\x88\xa3\x1e\x00B\x15Z\x13remes/x/remes/typesb\x06proto3"

var (
	file_remes_remes_v1_node_proto_rawDescOnce sync.Once
	file_remes_remes_v1_node_proto_rawDescData []byte
)

func file_remes_remes_v1_node_proto_rawDescGZIP() []byte {
	file_remes_remes_v1_node_proto_rawDescOnce.Do(func() {
		file_remes_remes_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remes_remes_v1_node_proto_rawDesc), len(file_remes_remes_v1_node_proto_rawDesc)))
	})
	return file_remes_remes_v1_node_proto_rawDescData
}

var file_remes_remes_v1_node_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_remes_remes_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_remes_remes_v1_node_proto_goTypes = []any{
	(NodeType)(0),                 // 0: remes.remes.v1.NodeType
	(NodeStatus)(0),               // 1: remes.remes.v1.NodeStatus
	(*ResourceSpec)(nil),          // 2: remes.remes.v1.ResourceSpec
	(*ResourceQuota)(nil),         // 3: remes.remes.v1.ResourceQuota
	(*NodeRegistration)(nil),      // 4: remes.remes.v1.NodeRegistration
	(*RoleAllocation)(nil),        // 5: remes.remes.v1.RoleAllocation
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_remes_remes_v1_node_proto_depIdxs = []int32{
	0, // 0: remes.remes.v1.ResourceQuota.role:type_name -> remes.remes.v1.NodeType
	0, // 1: remes.remes.v1.NodeRegistration.node_type:type_name -> remes.remes.v1.NodeType
	2, // 2: remes.remes.v1.NodeRegistration.resources:type_name -> remes.remes.v1.ResourceSpec
	1, // 3: remes.remes.v1.NodeRegistration.status:type_name -> remes.remes.v1.NodeStatus
	0, // 4: remes.remes.v1.NodeRegistration.roles:type_name -> remes.remes.v1.NodeType
	5, // 5: remes.remes.v1.NodeRegistration.role_allocations:type_name -> remes.remes.v1.RoleAllocation
	6, // 6: remes.remes.v1.NodeRegistration.registered_at_time:type_name -> google.protobuf.Timestamp
	0, // 7: remes.remes.v1.RoleAllocation.role:type_name -> remes.remes.v1.NodeType
	3, // 8: remes.remes.v1.RoleAllocation.quota:type_name -> remes.remes.v1.ResourceQuota
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_remes_remes_v1_node_proto_init() }
func file_remes_remes_v1_node_proto_init() {
	if File_remes_remes_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remes_remes_v1_node_proto_rawDesc), len(file_remes_remes_v1_node_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_remes_remes_v1_node_proto_goTypes,
		DependencyIndexes: file_remes_remes_v1_node_proto_depIdxs,
		EnumInfos:         file_remes_remes_v1_node_proto_enumTypes,
		MessageInfos:      file_remes_remes_v1_node_proto_msgTypes,
	}.Build()
	File_remes_remes_v1_node_proto = out.File
	file_remes_remes_v1_node_proto_goTypes = nil
	file_remes_remes_v1_node_proto_depIdxs = nil
}
