// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: remes/remes/v1/params.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Params defines the parameters for the module.
type Params struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_remes_remes_v1_params_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_remes_remes_v1_params_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_remes_remes_v1_params_proto_rawDescGZIP(), []int{0}
}

var File_remes_remes_v1_params_proto protoreflect.FileDescriptor

const file_remes_remes_v1_params_proto_rawDesc = "" +
	"\n" +
	"\x1bremes/remes/v1/params.proto\x12\x0eremes.remes.v1\x1a\x11amino/amino.proto\x1a\x14gogoproto/gogo.proto\"'\n" +
	"\x06Params:\x1d\xe8\xa0\x1f\x01\x8a\xe7\xb0*\x14remes/x/remes/ParamsB\x15Z\x13remes/x/remes/typesb\x06proto3"

var (
	file_remes_remes_v1_params_proto_rawDescOnce sync.Once
	file_remes_remes_v1_params_proto_rawDescData []byte
)

func file_remes_remes_v1_params_proto_rawDescGZIP() []byte {
	file_remes_remes_v1_params_proto_rawDescOnce.Do(func() {
		file_remes_remes_v1_params_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remes_remes_v1_params_proto_rawDesc), len(file_remes_remes_v1_params_proto_rawDesc)))
	})
	return file_remes_remes_v1_params_proto_rawDescData
}

var file_remes_remes_v1_params_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_remes_remes_v1_params_proto_goTypes = []any{
	(*Params)(nil), // 0: remes.remes.v1.Params
}
var file_remes_remes_v1_params_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_remes_remes_v1_params_proto_init() }
func file_remes_remes_v1_params_proto_init() {
	if File_remes_remes_v1_params_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remes_remes_v1_params_proto_rawDesc), len(file_remes_remes_v1_params_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_remes_remes_v1_params_proto_goTypes,
		DependencyIndexes: file_remes_remes_v1_params_proto_depIdxs,
		MessageInfos:      file_remes_remes_v1_params_proto_msgTypes,
	}.Build()
	File_remes_remes_v1_params_proto = out.File
	file_remes_remes_v1_params_proto_goTypes = nil
	file_remes_remes_v1_params_proto_depIdxs = nil
}
