// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: remes/remes/v1/query.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Query_Params_FullMethodName                    = "/remes.remes.v1.Query/Params"
	Query_GetGradient_FullMethodName               = "/remes.remes.v1.Query/GetGradient"
	Query_GetModelParams_FullMethodName            = "/remes.remes.v1.Query/GetModelParams"
	Query_GetAggregation_FullMethodName            = "/remes.remes.v1.Query/GetAggregation"
	Query_GetMinerScore_FullMethodName             = "/remes.remes.v1.Query/GetMinerScore"
	Query_ListStoredGradient_FullMethodName        = "/remes.remes.v1.Query/ListStoredGradient"
	Query_GetStoredGradient_FullMethodName         = "/remes.remes.v1.Query/GetStoredGradient"
	Query_GetDatasetProposal_FullMethodName        = "/remes.remes.v1.Query/GetDatasetProposal"
	Query_ListDatasetProposals_FullMethodName      = "/remes.remes.v1.Query/ListDatasetProposals"
	Query_GetApprovedDataset_FullMethodName        = "/remes.remes.v1.Query/GetApprovedDataset"
	Query_ListApprovedDatasets_FullMethodName      = "/remes.remes.v1.Query/ListApprovedDatasets"
	Query_GetNodeRegistration_FullMethodName       = "/remes.remes.v1.Query/GetNodeRegistration"
	Query_ListNodeRegistrations_FullMethodName     = "/remes.remes.v1.Query/ListNodeRegistrations"
	Query_GetInferenceRequest_FullMethodName       = "/remes.remes.v1.Query/GetInferenceRequest"
	Query_GetServingNodeStatus_FullMethodName      = "/remes.remes.v1.Query/GetServingNodeStatus"
	Query_ListServingNodes_FullMethodName          = "/remes.remes.v1.Query/ListServingNodes"
	Query_GetRewardFormula_FullMethodName          = "/remes.remes.v1.Query/GetRewardFormula"
	Query_GetParticipantSyncState_FullMethodName   = "/remes.remes.v1.Query/GetParticipantSyncState"
	Query_ListParticipantSyncStates_FullMethodName = "/remes.remes.v1.Query/ListParticipantSyncStates"
	Query_GetGlobalModelState_FullMethodName       = "/remes.remes.v1.Query/GetGlobalModelState"
	Query_GetCatchUpInfo_FullMethodName            = "/remes.remes.v1.Query/GetCatchUpInfo"
	Query_GetGlobalSeed_FullMethodName             = "/remes.remes.v1.Query/GetGlobalSeed"
	Query_QueryMiners_FullMethodName               = "/remes.remes.v1.Query/QueryMiners"
	Query_QueryStatistics_FullMethodName           = "/remes.remes.v1.Query/QueryStatistics"
	Query_QueryBlocks_FullMethodName               = "/remes.remes.v1.Query/QueryBlocks"
	Query_QueryBlock_FullMethodName                = "/remes.remes.v1.Query/QueryBlock"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the gRPC querier service.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// GetGradient queries a specific gradient by ID
	GetGradient(ctx context.Context, in *QueryGetGradientRequest, opts ...grpc.CallOption) (*QueryGetGradientResponse, error)
	// GetModelParams queries the current global model parameters (IPFS hash)
	GetModelParams(ctx context.Context, in *QueryGetModelParamsRequest, opts ...grpc.CallOption) (*QueryGetModelParamsResponse, error)
	// GetAggregation queries a specific aggregation by ID
	GetAggregation(ctx context.Context, in *QueryGetAggregationRequest, opts ...grpc.CallOption) (*QueryGetAggregationResponse, error)
	// GetMinerScore queries the reputation score and statistics for a miner
	GetMinerScore(ctx context.Context, in *QueryGetMinerScoreRequest, opts ...grpc.CallOption) (*QueryGetMinerScoreResponse, error)
	// ListStoredGradient queries all stored gradients with pagination
	ListStoredGradient(ctx context.Context, in *QueryListStoredGradientRequest, opts ...grpc.CallOption) (*QueryListStoredGradientResponse, error)
	// GetStoredGradient queries a specific stored gradient by ID
	GetStoredGradient(ctx context.Context, in *QueryGetStoredGradientRequest, opts ...grpc.CallOption) (*QueryGetStoredGradientResponse, error)
	// GetDatasetProposal queries a dataset proposal by ID
	GetDatasetProposal(ctx context.Context, in *QueryGetDatasetProposalRequest, opts ...grpc.CallOption) (*QueryGetDatasetProposalResponse, error)
	// ListDatasetProposals lists all dataset proposals
	ListDatasetProposals(ctx context.Context, in *QueryListDatasetProposalsRequest, opts ...grpc.CallOption) (*QueryListDatasetProposalsResponse, error)
	// GetApprovedDataset queries an approved dataset by ID
	GetApprovedDataset(ctx context.Context, in *QueryGetApprovedDatasetRequest, opts ...grpc.CallOption) (*QueryGetApprovedDatasetResponse, error)
	// ListApprovedDatasets lists all approved datasets
	ListApprovedDatasets(ctx context.Context, in *QueryListApprovedDatasetsRequest, opts ...grpc.CallOption) (*QueryListApprovedDatasetsResponse, error)
	// GetNodeRegistration queries a node registration by address
	GetNodeRegistration(ctx context.Context, in *QueryGetNodeRegistrationRequest, opts ...grpc.CallOption) (*QueryGetNodeRegistrationResponse, error)
	// ListNodeRegistrations lists all node registrations
	ListNodeRegistrations(ctx context.Context, in *QueryListNodeRegistrationsRequest, opts ...grpc.CallOption) (*QueryListNodeRegistrationsResponse, error)
	// GetInferenceRequest queries an inference request by ID
	GetInferenceRequest(ctx context.Context, in *QueryGetInferenceRequestRequest, opts ...grpc.CallOption) (*QueryGetInferenceRequestResponse, error)
	// GetServingNodeStatus queries serving node status
	GetServingNodeStatus(ctx context.Context, in *QueryGetServingNodeStatusRequest, opts ...grpc.CallOption) (*QueryGetServingNodeStatusResponse, error)
	// ListServingNodes lists all serving nodes
	ListServingNodes(ctx context.Context, in *QueryListServingNodesRequest, opts ...grpc.CallOption) (*QueryListServingNodesResponse, error)
	// GetRewardFormula queries transparent reward formulas
	GetRewardFormula(ctx context.Context, in *QueryGetRewardFormulaRequest, opts ...grpc.CallOption) (*QueryGetRewardFormulaResponse, error)
	// GetParticipantSyncState queries a participant's synchronization state
	GetParticipantSyncState(ctx context.Context, in *QueryGetParticipantSyncStateRequest, opts ...grpc.CallOption) (*QueryGetParticipantSyncStateResponse, error)
	// ListParticipantSyncStates lists all participant sync states with pagination
	ListParticipantSyncStates(ctx context.Context, in *QueryListParticipantSyncStatesRequest, opts ...grpc.CallOption) (*QueryListParticipantSyncStatesResponse, error)
	// GetGlobalModelState queries the current global model state
	GetGlobalModelState(ctx context.Context, in *QueryGetGlobalModelStateRequest, opts ...grpc.CallOption) (*QueryGetGlobalModelStateResponse, error)
	// GetCatchUpInfo returns information needed for a participant to catch up after network partition
	GetCatchUpInfo(ctx context.Context, in *QueryGetCatchUpInfoRequest, opts ...grpc.CallOption) (*QueryGetCatchUpInfoResponse, error)
	// GetGlobalSeed returns the global seed for a training round
	GetGlobalSeed(ctx context.Context, in *QueryGetGlobalSeedRequest, opts ...grpc.CallOption) (*QueryGetGlobalSeedResponse, error)
	// QueryMiners queries all miners with pagination (for dashboard API)
	QueryMiners(ctx context.Context, in *QueryMinersRequest, opts ...grpc.CallOption) (*QueryMinersResponse, error)
	// QueryStatistics queries network statistics (for dashboard API)
	QueryStatistics(ctx context.Context, in *QueryStatisticsRequest, opts ...grpc.CallOption) (*QueryStatisticsResponse, error)
	// QueryBlocks queries recent blocks with pagination (for dashboard API)
	QueryBlocks(ctx context.Context, in *QueryBlocksRequest, opts ...grpc.CallOption) (*QueryBlocksResponse, error)
	// QueryBlock queries a specific block by height (for dashboard API)
	QueryBlock(ctx context.Context, in *QueryBlockRequest, opts ...grpc.CallOption) (*QueryBlockResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetGradient(ctx context.Context, in *QueryGetGradientRequest, opts ...grpc.CallOption) (*QueryGetGradientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetGradientResponse)
	err := c.cc.Invoke(ctx, Query_GetGradient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetModelParams(ctx context.Context, in *QueryGetModelParamsRequest, opts ...grpc.CallOption) (*QueryGetModelParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetModelParamsResponse)
	err := c.cc.Invoke(ctx, Query_GetModelParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAggregation(ctx context.Context, in *QueryGetAggregationRequest, opts ...grpc.CallOption) (*QueryGetAggregationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetAggregationResponse)
	err := c.cc.Invoke(ctx, Query_GetAggregation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetMinerScore(ctx context.Context, in *QueryGetMinerScoreRequest, opts ...grpc.CallOption) (*QueryGetMinerScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetMinerScoreResponse)
	err := c.cc.Invoke(ctx, Query_GetMinerScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListStoredGradient(ctx context.Context, in *QueryListStoredGradientRequest, opts ...grpc.CallOption) (*QueryListStoredGradientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListStoredGradientResponse)
	err := c.cc.Invoke(ctx, Query_ListStoredGradient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetStoredGradient(ctx context.Context, in *QueryGetStoredGradientRequest, opts ...grpc.CallOption) (*QueryGetStoredGradientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetStoredGradientResponse)
	err := c.cc.Invoke(ctx, Query_GetStoredGradient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetDatasetProposal(ctx context.Context, in *QueryGetDatasetProposalRequest, opts ...grpc.CallOption) (*QueryGetDatasetProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetDatasetProposalResponse)
	err := c.cc.Invoke(ctx, Query_GetDatasetProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListDatasetProposals(ctx context.Context, in *QueryListDatasetProposalsRequest, opts ...grpc.CallOption) (*QueryListDatasetProposalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListDatasetProposalsResponse)
	err := c.cc.Invoke(ctx, Query_ListDatasetProposals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetApprovedDataset(ctx context.Context, in *QueryGetApprovedDatasetRequest, opts ...grpc.CallOption) (*QueryGetApprovedDatasetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetApprovedDatasetResponse)
	err := c.cc.Invoke(ctx, Query_GetApprovedDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListApprovedDatasets(ctx context.Context, in *QueryListApprovedDatasetsRequest, opts ...grpc.CallOption) (*QueryListApprovedDatasetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListApprovedDatasetsResponse)
	err := c.cc.Invoke(ctx, Query_ListApprovedDatasets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetNodeRegistration(ctx context.Context, in *QueryGetNodeRegistrationRequest, opts ...grpc.CallOption) (*QueryGetNodeRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetNodeRegistrationResponse)
	err := c.cc.Invoke(ctx, Query_GetNodeRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListNodeRegistrations(ctx context.Context, in *QueryListNodeRegistrationsRequest, opts ...grpc.CallOption) (*QueryListNodeRegistrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListNodeRegistrationsResponse)
	err := c.cc.Invoke(ctx, Query_ListNodeRegistrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetInferenceRequest(ctx context.Context, in *QueryGetInferenceRequestRequest, opts ...grpc.CallOption) (*QueryGetInferenceRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetInferenceRequestResponse)
	err := c.cc.Invoke(ctx, Query_GetInferenceRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetServingNodeStatus(ctx context.Context, in *QueryGetServingNodeStatusRequest, opts ...grpc.CallOption) (*QueryGetServingNodeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetServingNodeStatusResponse)
	err := c.cc.Invoke(ctx, Query_GetServingNodeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListServingNodes(ctx context.Context, in *QueryListServingNodesRequest, opts ...grpc.CallOption) (*QueryListServingNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListServingNodesResponse)
	err := c.cc.Invoke(ctx, Query_ListServingNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetRewardFormula(ctx context.Context, in *QueryGetRewardFormulaRequest, opts ...grpc.CallOption) (*QueryGetRewardFormulaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetRewardFormulaResponse)
	err := c.cc.Invoke(ctx, Query_GetRewardFormula_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetParticipantSyncState(ctx context.Context, in *QueryGetParticipantSyncStateRequest, opts ...grpc.CallOption) (*QueryGetParticipantSyncStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetParticipantSyncStateResponse)
	err := c.cc.Invoke(ctx, Query_GetParticipantSyncState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListParticipantSyncStates(ctx context.Context, in *QueryListParticipantSyncStatesRequest, opts ...grpc.CallOption) (*QueryListParticipantSyncStatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListParticipantSyncStatesResponse)
	err := c.cc.Invoke(ctx, Query_ListParticipantSyncStates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetGlobalModelState(ctx context.Context, in *QueryGetGlobalModelStateRequest, opts ...grpc.CallOption) (*QueryGetGlobalModelStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetGlobalModelStateResponse)
	err := c.cc.Invoke(ctx, Query_GetGlobalModelState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetCatchUpInfo(ctx context.Context, in *QueryGetCatchUpInfoRequest, opts ...grpc.CallOption) (*QueryGetCatchUpInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetCatchUpInfoResponse)
	err := c.cc.Invoke(ctx, Query_GetCatchUpInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetGlobalSeed(ctx context.Context, in *QueryGetGlobalSeedRequest, opts ...grpc.CallOption) (*QueryGetGlobalSeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetGlobalSeedResponse)
	err := c.cc.Invoke(ctx, Query_GetGlobalSeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryMiners(ctx context.Context, in *QueryMinersRequest, opts ...grpc.CallOption) (*QueryMinersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryMinersResponse)
	err := c.cc.Invoke(ctx, Query_QueryMiners_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryStatistics(ctx context.Context, in *QueryStatisticsRequest, opts ...grpc.CallOption) (*QueryStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryStatisticsResponse)
	err := c.cc.Invoke(ctx, Query_QueryStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryBlocks(ctx context.Context, in *QueryBlocksRequest, opts ...grpc.CallOption) (*QueryBlocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryBlocksResponse)
	err := c.cc.Invoke(ctx, Query_QueryBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryBlock(ctx context.Context, in *QueryBlockRequest, opts ...grpc.CallOption) (*QueryBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryBlockResponse)
	err := c.cc.Invoke(ctx, Query_QueryBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
//
// Query defines the gRPC querier service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// GetGradient queries a specific gradient by ID
	GetGradient(context.Context, *QueryGetGradientRequest) (*QueryGetGradientResponse, error)
	// GetModelParams queries the current global model parameters (IPFS hash)
	GetModelParams(context.Context, *QueryGetModelParamsRequest) (*QueryGetModelParamsResponse, error)
	// GetAggregation queries a specific aggregation by ID
	GetAggregation(context.Context, *QueryGetAggregationRequest) (*QueryGetAggregationResponse, error)
	// GetMinerScore queries the reputation score and statistics for a miner
	GetMinerScore(context.Context, *QueryGetMinerScoreRequest) (*QueryGetMinerScoreResponse, error)
	// ListStoredGradient queries all stored gradients with pagination
	ListStoredGradient(context.Context, *QueryListStoredGradientRequest) (*QueryListStoredGradientResponse, error)
	// GetStoredGradient queries a specific stored gradient by ID
	GetStoredGradient(context.Context, *QueryGetStoredGradientRequest) (*QueryGetStoredGradientResponse, error)
	// GetDatasetProposal queries a dataset proposal by ID
	GetDatasetProposal(context.Context, *QueryGetDatasetProposalRequest) (*QueryGetDatasetProposalResponse, error)
	// ListDatasetProposals lists all dataset proposals
	ListDatasetProposals(context.Context, *QueryListDatasetProposalsRequest) (*QueryListDatasetProposalsResponse, error)
	// GetApprovedDataset queries an approved dataset by ID
	GetApprovedDataset(context.Context, *QueryGetApprovedDatasetRequest) (*QueryGetApprovedDatasetResponse, error)
	// ListApprovedDatasets lists all approved datasets
	ListApprovedDatasets(context.Context, *QueryListApprovedDatasetsRequest) (*QueryListApprovedDatasetsResponse, error)
	// GetNodeRegistration queries a node registration by address
	GetNodeRegistration(context.Context, *QueryGetNodeRegistrationRequest) (*QueryGetNodeRegistrationResponse, error)
	// ListNodeRegistrations lists all node registrations
	ListNodeRegistrations(context.Context, *QueryListNodeRegistrationsRequest) (*QueryListNodeRegistrationsResponse, error)
	// GetInferenceRequest queries an inference request by ID
	GetInferenceRequest(context.Context, *QueryGetInferenceRequestRequest) (*QueryGetInferenceRequestResponse, error)
	// GetServingNodeStatus queries serving node status
	GetServingNodeStatus(context.Context, *QueryGetServingNodeStatusRequest) (*QueryGetServingNodeStatusResponse, error)
	// ListServingNodes lists all serving nodes
	ListServingNodes(context.Context, *QueryListServingNodesRequest) (*QueryListServingNodesResponse, error)
	// GetRewardFormula queries transparent reward formulas
	GetRewardFormula(context.Context, *QueryGetRewardFormulaRequest) (*QueryGetRewardFormulaResponse, error)
	// GetParticipantSyncState queries a participant's synchronization state
	GetParticipantSyncState(context.Context, *QueryGetParticipantSyncStateRequest) (*QueryGetParticipantSyncStateResponse, error)
	// ListParticipantSyncStates lists all participant sync states with pagination
	ListParticipantSyncStates(context.Context, *QueryListParticipantSyncStatesRequest) (*QueryListParticipantSyncStatesResponse, error)
	// GetGlobalModelState queries the current global model state
	GetGlobalModelState(context.Context, *QueryGetGlobalModelStateRequest) (*QueryGetGlobalModelStateResponse, error)
	// GetCatchUpInfo returns information needed for a participant to catch up after network partition
	GetCatchUpInfo(context.Context, *QueryGetCatchUpInfoRequest) (*QueryGetCatchUpInfoResponse, error)
	// GetGlobalSeed returns the global seed for a training round
	GetGlobalSeed(context.Context, *QueryGetGlobalSeedRequest) (*QueryGetGlobalSeedResponse, error)
	// QueryMiners queries all miners with pagination (for dashboard API)
	QueryMiners(context.Context, *QueryMinersRequest) (*QueryMinersResponse, error)
	// QueryStatistics queries network statistics (for dashboard API)
	QueryStatistics(context.Context, *QueryStatisticsRequest) (*QueryStatisticsResponse, error)
	// QueryBlocks queries recent blocks with pagination (for dashboard API)
	QueryBlocks(context.Context, *QueryBlocksRequest) (*QueryBlocksResponse, error)
	// QueryBlock queries a specific block by height (for dashboard API)
	QueryBlock(context.Context, *QueryBlockRequest) (*QueryBlockResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) GetGradient(context.Context, *QueryGetGradientRequest) (*QueryGetGradientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGradient not implemented")
}
func (UnimplementedQueryServer) GetModelParams(context.Context, *QueryGetModelParamsRequest) (*QueryGetModelParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelParams not implemented")
}
func (UnimplementedQueryServer) GetAggregation(context.Context, *QueryGetAggregationRequest) (*QueryGetAggregationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAggregation not implemented")
}
func (UnimplementedQueryServer) GetMinerScore(context.Context, *QueryGetMinerScoreRequest) (*QueryGetMinerScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMinerScore not implemented")
}
func (UnimplementedQueryServer) ListStoredGradient(context.Context, *QueryListStoredGradientRequest) (*QueryListStoredGradientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStoredGradient not implemented")
}
func (UnimplementedQueryServer) GetStoredGradient(context.Context, *QueryGetStoredGradientRequest) (*QueryGetStoredGradientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStoredGradient not implemented")
}
func (UnimplementedQueryServer) GetDatasetProposal(context.Context, *QueryGetDatasetProposalRequest) (*QueryGetDatasetProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatasetProposal not implemented")
}
func (UnimplementedQueryServer) ListDatasetProposals(context.Context, *QueryListDatasetProposalsRequest) (*QueryListDatasetProposalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDatasetProposals not implemented")
}
func (UnimplementedQueryServer) GetApprovedDataset(context.Context, *QueryGetApprovedDatasetRequest) (*QueryGetApprovedDatasetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApprovedDataset not implemented")
}
func (UnimplementedQueryServer) ListApprovedDatasets(context.Context, *QueryListApprovedDatasetsRequest) (*QueryListApprovedDatasetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApprovedDatasets not implemented")
}
func (UnimplementedQueryServer) GetNodeRegistration(context.Context, *QueryGetNodeRegistrationRequest) (*QueryGetNodeRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeRegistration not implemented")
}
func (UnimplementedQueryServer) ListNodeRegistrations(context.Context, *QueryListNodeRegistrationsRequest) (*QueryListNodeRegistrationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodeRegistrations not implemented")
}
func (UnimplementedQueryServer) GetInferenceRequest(context.Context, *QueryGetInferenceRequestRequest) (*QueryGetInferenceRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInferenceRequest not implemented")
}
func (UnimplementedQueryServer) GetServingNodeStatus(context.Context, *QueryGetServingNodeStatusRequest) (*QueryGetServingNodeStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServingNodeStatus not implemented")
}
func (UnimplementedQueryServer) ListServingNodes(context.Context, *QueryListServingNodesRequest) (*QueryListServingNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServingNodes not implemented")
}
func (UnimplementedQueryServer) GetRewardFormula(context.Context, *QueryGetRewardFormulaRequest) (*QueryGetRewardFormulaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRewardFormula not implemented")
}
func (UnimplementedQueryServer) GetParticipantSyncState(context.Context, *QueryGetParticipantSyncStateRequest) (*QueryGetParticipantSyncStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParticipantSyncState not implemented")
}
func (UnimplementedQueryServer) ListParticipantSyncStates(context.Context, *QueryListParticipantSyncStatesRequest) (*QueryListParticipantSyncStatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListParticipantSyncStates not implemented")
}
func (UnimplementedQueryServer) GetGlobalModelState(context.Context, *QueryGetGlobalModelStateRequest) (*QueryGetGlobalModelStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGlobalModelState not implemented")
}
func (UnimplementedQueryServer) GetCatchUpInfo(context.Context, *QueryGetCatchUpInfoRequest) (*QueryGetCatchUpInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCatchUpInfo not implemented")
}
func (UnimplementedQueryServer) GetGlobalSeed(context.Context, *QueryGetGlobalSeedRequest) (*QueryGetGlobalSeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGlobalSeed not implemented")
}
func (UnimplementedQueryServer) QueryMiners(context.Context, *QueryMinersRequest) (*QueryMinersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMiners not implemented")
}
func (UnimplementedQueryServer) QueryStatistics(context.Context, *QueryStatisticsRequest) (*QueryStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryStatistics not implemented")
}
func (UnimplementedQueryServer) QueryBlocks(context.Context, *QueryBlocksRequest) (*QueryBlocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryBlocks not implemented")
}
func (UnimplementedQueryServer) QueryBlock(context.Context, *QueryBlockRequest) (*QueryBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryBlock not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetGradient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetGradientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetGradient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetGradient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetGradient(ctx, req.(*QueryGetGradientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetModelParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetModelParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetModelParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetModelParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetModelParams(ctx, req.(*QueryGetModelParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAggregation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAggregationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAggregation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetAggregation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAggregation(ctx, req.(*QueryGetAggregationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetMinerScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMinerScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetMinerScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetMinerScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetMinerScore(ctx, req.(*QueryGetMinerScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListStoredGradient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListStoredGradientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListStoredGradient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListStoredGradient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListStoredGradient(ctx, req.(*QueryListStoredGradientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetStoredGradient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetStoredGradientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetStoredGradient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetStoredGradient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetStoredGradient(ctx, req.(*QueryGetStoredGradientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetDatasetProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDatasetProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetDatasetProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetDatasetProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetDatasetProposal(ctx, req.(*QueryGetDatasetProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListDatasetProposals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListDatasetProposalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListDatasetProposals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListDatasetProposals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListDatasetProposals(ctx, req.(*QueryListDatasetProposalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetApprovedDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetApprovedDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetApprovedDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetApprovedDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetApprovedDataset(ctx, req.(*QueryGetApprovedDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListApprovedDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListApprovedDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListApprovedDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListApprovedDatasets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListApprovedDatasets(ctx, req.(*QueryListApprovedDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetNodeRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNodeRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetNodeRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetNodeRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetNodeRegistration(ctx, req.(*QueryGetNodeRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListNodeRegistrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListNodeRegistrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListNodeRegistrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListNodeRegistrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListNodeRegistrations(ctx, req.(*QueryListNodeRegistrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetInferenceRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetInferenceRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetInferenceRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetInferenceRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetInferenceRequest(ctx, req.(*QueryGetInferenceRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetServingNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetServingNodeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetServingNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetServingNodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetServingNodeStatus(ctx, req.(*QueryGetServingNodeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListServingNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListServingNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListServingNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListServingNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListServingNodes(ctx, req.(*QueryListServingNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetRewardFormula_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRewardFormulaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetRewardFormula(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetRewardFormula_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetRewardFormula(ctx, req.(*QueryGetRewardFormulaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetParticipantSyncState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetParticipantSyncStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetParticipantSyncState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetParticipantSyncState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetParticipantSyncState(ctx, req.(*QueryGetParticipantSyncStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListParticipantSyncStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListParticipantSyncStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListParticipantSyncStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListParticipantSyncStates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListParticipantSyncStates(ctx, req.(*QueryListParticipantSyncStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetGlobalModelState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetGlobalModelStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetGlobalModelState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetGlobalModelState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetGlobalModelState(ctx, req.(*QueryGetGlobalModelStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetCatchUpInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCatchUpInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetCatchUpInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetCatchUpInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetCatchUpInfo(ctx, req.(*QueryGetCatchUpInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetGlobalSeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetGlobalSeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetGlobalSeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetGlobalSeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetGlobalSeed(ctx, req.(*QueryGetGlobalSeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryMiners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMinersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryMiners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_QueryMiners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryMiners(ctx, req.(*QueryMinersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_QueryStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryStatistics(ctx, req.(*QueryStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_QueryBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryBlocks(ctx, req.(*QueryBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_QueryBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryBlock(ctx, req.(*QueryBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remes.remes.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetGradient",
			Handler:    _Query_GetGradient_Handler,
		},
		{
			MethodName: "GetModelParams",
			Handler:    _Query_GetModelParams_Handler,
		},
		{
			MethodName: "GetAggregation",
			Handler:    _Query_GetAggregation_Handler,
		},
		{
			MethodName: "GetMinerScore",
			Handler:    _Query_GetMinerScore_Handler,
		},
		{
			MethodName: "ListStoredGradient",
			Handler:    _Query_ListStoredGradient_Handler,
		},
		{
			MethodName: "GetStoredGradient",
			Handler:    _Query_GetStoredGradient_Handler,
		},
		{
			MethodName: "GetDatasetProposal",
			Handler:    _Query_GetDatasetProposal_Handler,
		},
		{
			MethodName: "ListDatasetProposals",
			Handler:    _Query_ListDatasetProposals_Handler,
		},
		{
			MethodName: "GetApprovedDataset",
			Handler:    _Query_GetApprovedDataset_Handler,
		},
		{
			MethodName: "ListApprovedDatasets",
			Handler:    _Query_ListApprovedDatasets_Handler,
		},
		{
			MethodName: "GetNodeRegistration",
			Handler:    _Query_GetNodeRegistration_Handler,
		},
		{
			MethodName: "ListNodeRegistrations",
			Handler:    _Query_ListNodeRegistrations_Handler,
		},
		{
			MethodName: "GetInferenceRequest",
			Handler:    _Query_GetInferenceRequest_Handler,
		},
		{
			MethodName: "GetServingNodeStatus",
			Handler:    _Query_GetServingNodeStatus_Handler,
		},
		{
			MethodName: "ListServingNodes",
			Handler:    _Query_ListServingNodes_Handler,
		},
		{
			MethodName: "GetRewardFormula",
			Handler:    _Query_GetRewardFormula_Handler,
		},
		{
			MethodName: "GetParticipantSyncState",
			Handler:    _Query_GetParticipantSyncState_Handler,
		},
		{
			MethodName: "ListParticipantSyncStates",
			Handler:    _Query_ListParticipantSyncStates_Handler,
		},
		{
			MethodName: "GetGlobalModelState",
			Handler:    _Query_GetGlobalModelState_Handler,
		},
		{
			MethodName: "GetCatchUpInfo",
			Handler:    _Query_GetCatchUpInfo_Handler,
		},
		{
			MethodName: "GetGlobalSeed",
			Handler:    _Query_GetGlobalSeed_Handler,
		},
		{
			MethodName: "QueryMiners",
			Handler:    _Query_QueryMiners_Handler,
		},
		{
			MethodName: "QueryStatistics",
			Handler:    _Query_QueryStatistics_Handler,
		},
		{
			MethodName: "QueryBlocks",
			Handler:    _Query_QueryBlocks_Handler,
		},
		{
			MethodName: "QueryBlock",
			Handler:    _Query_QueryBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "remes/remes/v1/query.proto",
}
