// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: remes/remes/v1/stored_gradient.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StoredGradient represents a gradient submission stored on-chain
// Only metadata and IPFS hash are stored, NOT the actual gradient data
type StoredGradient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier for this gradient submission
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// miner is the address of the miner who submitted the gradient
	Miner string `protobuf:"bytes,2,opt,name=miner,proto3" json:"miner,omitempty"`
	// ipfs_hash is the IPFS content hash of the gradient data
	IpfsHash string `protobuf:"bytes,3,opt,name=ipfs_hash,json=ipfsHash,proto3" json:"ipfs_hash,omitempty"`
	// model_version is the version of the model used for training
	// DEPRECATED: Use model_config_id instead. Kept for backward compatibility.
	ModelVersion string `protobuf:"bytes,4,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	// training_round_id is the identifier for the training round
	TrainingRoundId uint64 `protobuf:"varint,5,opt,name=training_round_id,json=trainingRoundId,proto3" json:"training_round_id,omitempty"`
	// shard_id is the deterministic shard assignment for this miner
	ShardId uint64 `protobuf:"varint,6,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// gradient_hash is the deterministic hash of the gradient for verification
	GradientHash string `protobuf:"bytes,7,opt,name=gradient_hash,json=gradientHash,proto3" json:"gradient_hash,omitempty"`
	// gpu_architecture is the GPU architecture used (Ampere, Ada, Blackwell, etc.)
	GpuArchitecture string `protobuf:"bytes,8,opt,name=gpu_architecture,json=gpuArchitecture,proto3" json:"gpu_architecture,omitempty"`
	// submitted_at_height is the block height when this gradient was submitted
	SubmittedAtHeight int64 `protobuf:"varint,9,opt,name=submitted_at_height,json=submittedAtHeight,proto3" json:"submitted_at_height,omitempty"`
	// status is the current status of the gradient (pending, aggregated, challenged)
	Status string `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	// model_config_id references the ModelRegistry entry
	// This enables model-agnostic gradient storage
	// Default: 0 (legacy BitNet model, will be migrated automatically)
	ModelConfigId uint64 `protobuf:"varint,11,opt,name=model_config_id,json=modelConfigId,proto3" json:"model_config_id,omitempty"`
	// encryption_type specifies how this gradient is encrypted
	EncryptionType EncryptionType `protobuf:"varint,12,opt,name=encryption_type,json=encryptionType,proto3,enum=remes.remes.v1.EncryptionType" json:"encryption_type,omitempty"`
	// encrypted_gradient_ipfs_hash is the IPFS hash of encrypted gradient
	// Only used if encryption_type != ENCRYPTION_TYPE_PLAINTEXT
	EncryptedGradientIpfsHash string `protobuf:"bytes,13,opt,name=encrypted_gradient_ipfs_hash,json=encryptedGradientIpfsHash,proto3" json:"encrypted_gradient_ipfs_hash,omitempty"`
	// container_hash is the Docker/OCI image hash used for training
	ContainerHash string `protobuf:"bytes,14,opt,name=container_hash,json=containerHash,proto3" json:"container_hash,omitempty"`
	// container_signature is the cryptographic signature of the container
	ContainerSignature []byte `protobuf:"bytes,15,opt,name=container_signature,json=containerSignature,proto3" json:"container_signature,omitempty"`
	// global_seed is the deterministic seed used for training (derived from block hash + training round)
	GlobalSeed uint64 `protobuf:"varint,16,opt,name=global_seed,json=globalSeed,proto3" json:"global_seed,omitempty"`
	// claimed_loss is the loss value claimed by the miner (BitNet integer format)
	// Used for Loss-Based Spot Checking in Layer 2 verification
	ClaimedLoss string `protobuf:"bytes,17,opt,name=claimed_loss,json=claimedLoss,proto3" json:"claimed_loss,omitempty"`
	// porep_proof_ipfs_hash is the IPFS hash of the Proof of Replication (PoRep) proof
	// PoRep proves that the miner actually stores the gradient data, not just the hash
	PorepProofIpfsHash string `protobuf:"bytes,18,opt,name=porep_proof_ipfs_hash,json=porepProofIpfsHash,proto3" json:"porep_proof_ipfs_hash,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StoredGradient) Reset() {
	*x = StoredGradient{}
	mi := &file_remes_remes_v1_stored_gradient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredGradient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredGradient) ProtoMessage() {}

func (x *StoredGradient) ProtoReflect() protoreflect.Message {
	mi := &file_remes_remes_v1_stored_gradient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredGradient.ProtoReflect.Descriptor instead.
func (*StoredGradient) Descriptor() ([]byte, []int) {
	return file_remes_remes_v1_stored_gradient_proto_rawDescGZIP(), []int{0}
}

func (x *StoredGradient) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StoredGradient) GetMiner() string {
	if x != nil {
		return x.Miner
	}
	return ""
}

func (x *StoredGradient) GetIpfsHash() string {
	if x != nil {
		return x.IpfsHash
	}
	return ""
}

func (x *StoredGradient) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *StoredGradient) GetTrainingRoundId() uint64 {
	if x != nil {
		return x.TrainingRoundId
	}
	return 0
}

func (x *StoredGradient) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *StoredGradient) GetGradientHash() string {
	if x != nil {
		return x.GradientHash
	}
	return ""
}

func (x *StoredGradient) GetGpuArchitecture() string {
	if x != nil {
		return x.GpuArchitecture
	}
	return ""
}

func (x *StoredGradient) GetSubmittedAtHeight() int64 {
	if x != nil {
		return x.SubmittedAtHeight
	}
	return 0
}

func (x *StoredGradient) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StoredGradient) GetModelConfigId() uint64 {
	if x != nil {
		return x.ModelConfigId
	}
	return 0
}

func (x *StoredGradient) GetEncryptionType() EncryptionType {
	if x != nil {
		return x.EncryptionType
	}
	return EncryptionType_ENCRYPTION_TYPE_UNSPECIFIED
}

func (x *StoredGradient) GetEncryptedGradientIpfsHash() string {
	if x != nil {
		return x.EncryptedGradientIpfsHash
	}
	return ""
}

func (x *StoredGradient) GetContainerHash() string {
	if x != nil {
		return x.ContainerHash
	}
	return ""
}

func (x *StoredGradient) GetContainerSignature() []byte {
	if x != nil {
		return x.ContainerSignature
	}
	return nil
}

func (x *StoredGradient) GetGlobalSeed() uint64 {
	if x != nil {
		return x.GlobalSeed
	}
	return 0
}

func (x *StoredGradient) GetClaimedLoss() string {
	if x != nil {
		return x.ClaimedLoss
	}
	return ""
}

func (x *StoredGradient) GetPorepProofIpfsHash() string {
	if x != nil {
		return x.PorepProofIpfsHash
	}
	return ""
}

var File_remes_remes_v1_stored_gradient_proto protoreflect.FileDescriptor

const file_remes_remes_v1_stored_gradient_proto_rawDesc = "" +
	"\n" +
	"$remes/remes/v1/stored_gradient.proto\x12\x0eremes.remes.v1\x1a\x11amino/amino.proto\x1a\x14gogoproto/gogo.proto\x1a\x1aremes/remes/v1/model.proto\"\xff\x05\n" +
	"\x0eStoredGradient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05miner\x18\x02 \x01(\tR\x05miner\x12\x1b\n" +
	"\tipfs_hash\x18\x03 \x01(\tR\bipfsHash\x12#\n" +
	"\rmodel_version\x18\x04 \x01(\tR\fmodelVersion\x12*\n" +
	"\x11training_round_id\x18\x05 \x01(\x04R\x0ftrainingRoundId\x12\x19\n" +
	"\bshard_id\x18\x06 \x01(\x04R\ashardId\x12#\n" +
	"\rgradient_hash\x18\a \x01(\tR\fgradientHash\x12)\n" +
	"\x10gpu_architecture\x18\b \x01(\tR\x0fgpuArchitecture\x12.\n" +
	"\x13submitted_at_height\x18\t \x01(\x03R\x11submittedAtHeight\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12&\n" +
	"\x0fmodel_config_id\x18\v \x01(\x04R\rmodelConfigId\x12G\n" +
	"\x0fencryption_type\x18\f \x01(\x0e2\x1e.remes.remes.v1.EncryptionTypeR\x0eencryptionType\x12?\n" +
	"\x1cencrypted_gradient_ipfs_hash\x18\r \x01(\tR\x19encryptedGradientIpfsHash\x12%\n" +
	"\x0econtainer_hash\x18\x0e \x01(\tR\rcontainerHash\x12/\n" +
	"\x13container_signature\x18\x0f \x01(\fR\x12containerSignature\x12\x1f\n" +
	"\vglobal_seed\x18\x10 \x01(\x04R\n" +
	"globalSeed\x12!\n" +
	"\fclaimed_loss\x18\x11 \x01(\tR\vclaimedLoss\x121\n" +
	"\x15porep_proof_ipfs_hash\x18\x12 \x01(\tR\x12porepProofIpfsHash:%\xe8\xa0\x1f\x01\x8a\xe7\xb0*\x1cremes/x/remes/StoredGradientB\x15Z\x13remes/x/remes/typesb\x06proto3"

var (
	file_remes_remes_v1_stored_gradient_proto_rawDescOnce sync.Once
	file_remes_remes_v1_stored_gradient_proto_rawDescData []byte
)

func file_remes_remes_v1_stored_gradient_proto_rawDescGZIP() []byte {
	file_remes_remes_v1_stored_gradient_proto_rawDescOnce.Do(func() {
		file_remes_remes_v1_stored_gradient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remes_remes_v1_stored_gradient_proto_rawDesc), len(file_remes_remes_v1_stored_gradient_proto_rawDesc)))
	})
	return file_remes_remes_v1_stored_gradient_proto_rawDescData
}

var file_remes_remes_v1_stored_gradient_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_remes_remes_v1_stored_gradient_proto_goTypes = []any{
	(*StoredGradient)(nil), // 0: remes.remes.v1.StoredGradient
	(EncryptionType)(0),    // 1: remes.remes.v1.EncryptionType
}
var file_remes_remes_v1_stored_gradient_proto_depIdxs = []int32{
	1, // 0: remes.remes.v1.StoredGradient.encryption_type:type_name -> remes.remes.v1.EncryptionType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_remes_remes_v1_stored_gradient_proto_init() }
func file_remes_remes_v1_stored_gradient_proto_init() {
	if File_remes_remes_v1_stored_gradient_proto != nil {
		return
	}
	file_remes_remes_v1_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remes_remes_v1_stored_gradient_proto_rawDesc), len(file_remes_remes_v1_stored_gradient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_remes_remes_v1_stored_gradient_proto_goTypes,
		DependencyIndexes: file_remes_remes_v1_stored_gradient_proto_depIdxs,
		MessageInfos:      file_remes_remes_v1_stored_gradient_proto_msgTypes,
	}.Build()
	File_remes_remes_v1_stored_gradient_proto = out.File
	file_remes_remes_v1_stored_gradient_proto_goTypes = nil
	file_remes_remes_v1_stored_gradient_proto_depIdxs = nil
}
