// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: remes/remes/module/v1/module.proto

package types

import (
	_ "cosmossdk.io/depinject/appconfig/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Module is the config object for the module.
type Module struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// authority defines the custom module authority.
	// If not set, defaults to the governance module.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// ipfs_api_url defines the IPFS API URL for passive content retrieval.
	// Default: http://127.0.0.1:5001
	IpfsApiUrl    string `protobuf:"bytes,2,opt,name=ipfs_api_url,json=ipfsApiUrl,proto3" json:"ipfs_api_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_remes_remes_module_v1_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_remes_remes_module_v1_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_remes_remes_module_v1_module_proto_rawDescGZIP(), []int{0}
}

func (x *Module) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *Module) GetIpfsApiUrl() string {
	if x != nil {
		return x.IpfsApiUrl
	}
	return ""
}

var File_remes_remes_module_v1_module_proto protoreflect.FileDescriptor

const file_remes_remes_module_v1_module_proto_rawDesc = "" +
	"\n" +
	"\"remes/remes/module/v1/module.proto\x12\x15remes.remes.module.v1\x1a cosmos/app/v1alpha1/module.proto\"_\n" +
	"\x06Module\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12 \n" +
	"\fipfs_api_url\x18\x02 \x01(\tR\n" +
	"ipfsApiUrl:\x15\xba\xc0\x96\xda\x01\x0f\n" +
	"\rremes/x/remesB\x15Z\x13remes/x/remes/typesb\x06proto3"

var (
	file_remes_remes_module_v1_module_proto_rawDescOnce sync.Once
	file_remes_remes_module_v1_module_proto_rawDescData []byte
)

func file_remes_remes_module_v1_module_proto_rawDescGZIP() []byte {
	file_remes_remes_module_v1_module_proto_rawDescOnce.Do(func() {
		file_remes_remes_module_v1_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remes_remes_module_v1_module_proto_rawDesc), len(file_remes_remes_module_v1_module_proto_rawDesc)))
	})
	return file_remes_remes_module_v1_module_proto_rawDescData
}

var file_remes_remes_module_v1_module_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_remes_remes_module_v1_module_proto_goTypes = []any{
	(*Module)(nil), // 0: remes.remes.module.v1.Module
}
var file_remes_remes_module_v1_module_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_remes_remes_module_v1_module_proto_init() }
func file_remes_remes_module_v1_module_proto_init() {
	if File_remes_remes_module_v1_module_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remes_remes_module_v1_module_proto_rawDesc), len(file_remes_remes_module_v1_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_remes_remes_module_v1_module_proto_goTypes,
		DependencyIndexes: file_remes_remes_module_v1_module_proto_depIdxs,
		MessageInfos:      file_remes_remes_module_v1_module_proto_msgTypes,
	}.Build()
	File_remes_remes_module_v1_module_proto = out.File
	file_remes_remes_module_v1_module_proto_goTypes = nil
	file_remes_remes_module_v1_module_proto_depIdxs = nil
}
