// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: remes/remes/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// Challenge period blocks - number of blocks before aggregation can be finalized
	// Default: 100 blocks (~8 minutes at 5s/block)
	ChallengePeriodBlocks int64 `protobuf:"varint,1,opt,name=challenge_period_blocks,json=challengePeriodBlocks,proto3" json:"challenge_period_blocks,omitempty"`
	// Scalability parameters for adaptive scaling mechanisms
	ScalabilityParams ScalabilityParams `protobuf:"bytes,2,opt,name=scalability_params,json=scalabilityParams,proto3" json:"scalability_params"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_e73843849ab2fa2a, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetChallengePeriodBlocks() int64 {
	if m != nil {
		return m.ChallengePeriodBlocks
	}
	return 0
}

func (m *Params) GetScalabilityParams() ScalabilityParams {
	if m != nil {
		return m.ScalabilityParams
	}
	return ScalabilityParams{}
}

// ScalabilityParams holds configuration for adaptive scaling mechanisms
type ScalabilityParams struct {
	// Thresholds for adaptive scaling
	MaxParticipantsPerShard uint64 `protobuf:"varint,1,opt,name=max_participants_per_shard,json=maxParticipantsPerShard,proto3" json:"max_participants_per_shard,omitempty"`
	MaxGradientsPerBlock    uint64 `protobuf:"varint,2,opt,name=max_gradients_per_block,json=maxGradientsPerBlock,proto3" json:"max_gradients_per_block,omitempty"`
	MaxAggregationsPerBlock uint64 `protobuf:"varint,3,opt,name=max_aggregations_per_block,json=maxAggregationsPerBlock,proto3" json:"max_aggregations_per_block,omitempty"`
	MaxPendingGradients     uint64 `protobuf:"varint,4,opt,name=max_pending_gradients,json=maxPendingGradients,proto3" json:"max_pending_gradients,omitempty"`
	MaxPendingAggregations  uint64 `protobuf:"varint,5,opt,name=max_pending_aggregations,json=maxPendingAggregations,proto3" json:"max_pending_aggregations,omitempty"`
	// Adaptive parameters (as strings for decimal precision)
	CompressionRatioThreshold    string `protobuf:"bytes,6,opt,name=compression_ratio_threshold,json=compressionRatioThreshold,proto3" json:"compression_ratio_threshold,omitempty"`
	NetworkLoadThreshold         string `protobuf:"bytes,7,opt,name=network_load_threshold,json=networkLoadThreshold,proto3" json:"network_load_threshold,omitempty"`
	ResourceUtilizationThreshold string `protobuf:"bytes,8,opt,name=resource_utilization_threshold,json=resourceUtilizationThreshold,proto3" json:"resource_utilization_threshold,omitempty"`
	// Load balancing
	EnableLoadBalancing       bool   `protobuf:"varint,9,opt,name=enable_load_balancing,json=enableLoadBalancing,proto3" json:"enable_load_balancing,omitempty"`
	LoadBalancingStrategy     string `protobuf:"bytes,10,opt,name=load_balancing_strategy,json=loadBalancingStrategy,proto3" json:"load_balancing_strategy,omitempty"`
	ShardReassignmentInterval uint64 `protobuf:"varint,11,opt,name=shard_reassignment_interval,json=shardReassignmentInterval,proto3" json:"shard_reassignment_interval,omitempty"`
	// Performance optimization
	EnableAdaptiveCompression  bool `protobuf:"varint,12,opt,name=enable_adaptive_compression,json=enableAdaptiveCompression,proto3" json:"enable_adaptive_compression,omitempty"`
	EnableAdaptiveSharding     bool `protobuf:"varint,13,opt,name=enable_adaptive_sharding,json=enableAdaptiveSharding,proto3" json:"enable_adaptive_sharding,omitempty"`
	EnableResourceOptimization bool `protobuf:"varint,14,opt,name=enable_resource_optimization,json=enableResourceOptimization,proto3" json:"enable_resource_optimization,omitempty"`
}

func (m *ScalabilityParams) Reset()         { *m = ScalabilityParams{} }
func (m *ScalabilityParams) String() string { return proto.CompactTextString(m) }
func (*ScalabilityParams) ProtoMessage()    {}
func (*ScalabilityParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_e73843849ab2fa2a, []int{1}
}
func (m *ScalabilityParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ScalabilityParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ScalabilityParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ScalabilityParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalabilityParams.Merge(m, src)
}
func (m *ScalabilityParams) XXX_Size() int {
	return m.Size()
}
func (m *ScalabilityParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalabilityParams.DiscardUnknown(m)
}

var xxx_messageInfo_ScalabilityParams proto.InternalMessageInfo

func (m *ScalabilityParams) GetMaxParticipantsPerShard() uint64 {
	if m != nil {
		return m.MaxParticipantsPerShard
	}
	return 0
}

func (m *ScalabilityParams) GetMaxGradientsPerBlock() uint64 {
	if m != nil {
		return m.MaxGradientsPerBlock
	}
	return 0
}

func (m *ScalabilityParams) GetMaxAggregationsPerBlock() uint64 {
	if m != nil {
		return m.MaxAggregationsPerBlock
	}
	return 0
}

func (m *ScalabilityParams) GetMaxPendingGradients() uint64 {
	if m != nil {
		return m.MaxPendingGradients
	}
	return 0
}

func (m *ScalabilityParams) GetMaxPendingAggregations() uint64 {
	if m != nil {
		return m.MaxPendingAggregations
	}
	return 0
}

func (m *ScalabilityParams) GetCompressionRatioThreshold() string {
	if m != nil {
		return m.CompressionRatioThreshold
	}
	return ""
}

func (m *ScalabilityParams) GetNetworkLoadThreshold() string {
	if m != nil {
		return m.NetworkLoadThreshold
	}
	return ""
}

func (m *ScalabilityParams) GetResourceUtilizationThreshold() string {
	if m != nil {
		return m.ResourceUtilizationThreshold
	}
	return ""
}

func (m *ScalabilityParams) GetEnableLoadBalancing() bool {
	if m != nil {
		return m.EnableLoadBalancing
	}
	return false
}

func (m *ScalabilityParams) GetLoadBalancingStrategy() string {
	if m != nil {
		return m.LoadBalancingStrategy
	}
	return ""
}

func (m *ScalabilityParams) GetShardReassignmentInterval() uint64 {
	if m != nil {
		return m.ShardReassignmentInterval
	}
	return 0
}

func (m *ScalabilityParams) GetEnableAdaptiveCompression() bool {
	if m != nil {
		return m.EnableAdaptiveCompression
	}
	return false
}

func (m *ScalabilityParams) GetEnableAdaptiveSharding() bool {
	if m != nil {
		return m.EnableAdaptiveSharding
	}
	return false
}

func (m *ScalabilityParams) GetEnableResourceOptimization() bool {
	if m != nil {
		return m.EnableResourceOptimization
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "remes.remes.v1.Params")
	proto.RegisterType((*ScalabilityParams)(nil), "remes.remes.v1.ScalabilityParams")
}

func init() { proto.RegisterFile("remes/remes/v1/params.proto", fileDescriptor_e73843849ab2fa2a) }

var fileDescriptor_e73843849ab2fa2a = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x94, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x1b, 0x56, 0xf6, 0xc7, 0x83, 0x49, 0xcb, 0xda, 0x2d, 0xeb, 0x46, 0x56, 0x76, 0xaa,
	0x90, 0x68, 0xb5, 0xf1, 0x47, 0x68, 0x48, 0x88, 0x0d, 0x24, 0x84, 0x84, 0x44, 0x95, 0x02, 0x07,
	0x2e, 0x91, 0x9b, 0x58, 0xa9, 0xb5, 0xc4, 0x8e, 0x6c, 0xaf, 0x74, 0x9c, 0x38, 0x73, 0xe2, 0x23,
	0xf0, 0x11, 0xb8, 0xf1, 0x15, 0x76, 0xdc, 0x91, 0x13, 0x42, 0xdb, 0x01, 0x3e, 0x06, 0xf2, 0xeb,
	0xa4, 0x71, 0xb7, 0x8b, 0x15, 0xf9, 0xf9, 0x3d, 0x7e, 0xde, 0xf7, 0xad, 0x5d, 0xb4, 0x25, 0x48,
	0x46, 0x64, 0xcf, 0xac, 0xe3, 0xbd, 0x5e, 0x8e, 0x05, 0xce, 0x64, 0x37, 0x17, 0x5c, 0x71, 0x77,
	0x05, 0xb6, 0xbb, 0x66, 0x1d, 0xef, 0xb5, 0x56, 0x71, 0x46, 0x19, 0xef, 0xc1, 0x6a, 0x90, 0x56,
	0x23, 0xe1, 0x09, 0x87, 0xcf, 0x9e, 0xfe, 0x32, 0xbb, 0xbb, 0x3f, 0x1d, 0x34, 0xdf, 0x87, 0x93,
	0xdc, 0xc7, 0x68, 0x23, 0x1a, 0xe1, 0x34, 0x25, 0x2c, 0x21, 0x61, 0x4e, 0x04, 0xe5, 0x71, 0x38,
	0x4c, 0x79, 0x74, 0x2c, 0x3d, 0xa7, 0xed, 0x74, 0xe6, 0x82, 0xe6, 0x54, 0xee, 0x83, 0x7a, 0x04,
	0xa2, 0xfb, 0x01, 0xb9, 0x32, 0xc2, 0x29, 0x1e, 0xd2, 0x94, 0xaa, 0xd3, 0xd0, 0xd4, 0xe5, 0xdd,
	0x68, 0x3b, 0x9d, 0xe5, 0xfd, 0xbb, 0xdd, 0xd9, 0xc2, 0xba, 0x83, 0x8a, 0x34, 0xb1, 0x47, 0xf5,
	0xb3, 0xdf, 0x3b, 0xb5, 0x60, 0x55, 0x5e, 0x15, 0x0e, 0xee, 0xfc, 0xfb, 0xbe, 0xe3, 0x7c, 0xfd,
	0xfb, 0xe3, 0x5e, 0xc3, 0xf4, 0x3c, 0x29, 0x7a, 0x37, 0xf2, 0xee, 0x97, 0x05, 0xb4, 0x7a, 0xed,
	0x34, 0xf7, 0x29, 0x6a, 0x65, 0x78, 0xa2, 0x8b, 0x50, 0x34, 0xa2, 0x39, 0x66, 0x4a, 0xea, 0x5e,
	0x42, 0x39, 0xc2, 0x22, 0x86, 0x3e, 0xea, 0xc1, 0x46, 0x86, 0x27, 0x7d, 0x0b, 0xe8, 0x13, 0x31,
	0xd0, 0xb2, 0xfb, 0x08, 0x69, 0x29, 0x4c, 0x04, 0x8e, 0x29, 0x29, 0x9d, 0x30, 0x02, 0x68, 0xa7,
	0x1e, 0x34, 0x32, 0x3c, 0x79, 0x55, 0xaa, 0x7d, 0x22, 0x60, 0x02, 0x65, 0x26, 0x4e, 0x12, 0x41,
	0x12, 0xac, 0x28, 0x67, 0xb6, 0x73, 0x6e, 0x9a, 0x79, 0x68, 0x01, 0x53, 0xf3, 0x3e, 0x6a, 0x42,
	0xc1, 0x84, 0xc5, 0x94, 0x25, 0x55, 0xb6, 0x57, 0x07, 0xdf, 0x9a, 0xae, 0xd5, 0x68, 0xd3, 0x60,
	0xf7, 0x09, 0xf2, 0x6c, 0x8f, 0x1d, 0xec, 0xdd, 0x04, 0xdb, 0x7a, 0x65, 0xb3, 0x53, 0xdd, 0x67,
	0x68, 0x2b, 0xe2, 0x59, 0x2e, 0x88, 0x94, 0x94, 0xb3, 0x50, 0xe8, 0xed, 0x50, 0x8d, 0x04, 0x91,
	0x23, 0x9e, 0xc6, 0xde, 0x7c, 0xdb, 0xe9, 0x2c, 0x05, 0x9b, 0x16, 0x12, 0x68, 0xe2, 0x5d, 0x09,
	0xb8, 0x0f, 0xd1, 0x3a, 0x23, 0xea, 0x13, 0x17, 0xc7, 0x61, 0xca, 0x71, 0x6c, 0x59, 0x17, 0xc0,
	0xda, 0x28, 0xd4, 0x37, 0x1c, 0xc7, 0x95, 0xeb, 0x25, 0xf2, 0x05, 0x91, 0xfc, 0x44, 0x44, 0x24,
	0x3c, 0x51, 0x34, 0xa5, 0x9f, 0xa1, 0x1c, 0xcb, 0xbd, 0x08, 0xee, 0xed, 0x92, 0x7a, 0x5f, 0x41,
	0xd5, 0x29, 0xfb, 0xa8, 0x49, 0x18, 0x1e, 0xa6, 0xc4, 0x44, 0x0f, 0x71, 0x8a, 0x59, 0x44, 0x59,
	0xe2, 0x2d, 0xb5, 0x9d, 0xce, 0x62, 0xb0, 0x66, 0x44, 0x9d, 0x7c, 0x54, 0x4a, 0xfa, 0x4e, 0xcf,
	0xc2, 0xa1, 0x54, 0x02, 0x2b, 0x92, 0x9c, 0x7a, 0x08, 0x22, 0x9b, 0xa9, 0xcd, 0x0f, 0x0a, 0x51,
	0xcf, 0x09, 0x6e, 0x4c, 0x28, 0x08, 0x96, 0x92, 0x26, 0x2c, 0x23, 0x4c, 0x85, 0x94, 0x29, 0x22,
	0xc6, 0x38, 0xf5, 0x96, 0x61, 0xc8, 0x9b, 0x80, 0x04, 0x16, 0xf1, 0xba, 0x00, 0xb4, 0xbf, 0xa8,
	0x15, 0xc7, 0x38, 0x57, 0x74, 0x4c, 0x42, 0x6b, 0xa8, 0xde, 0x2d, 0xa8, 0x78, 0xd3, 0x20, 0x87,
	0x05, 0xf1, 0xa2, 0x02, 0xf4, 0x2f, 0x7c, 0xd5, 0x0f, 0x61, 0xba, 0xdd, 0xdb, 0x60, 0x5e, 0x9f,
	0x35, 0x0f, 0x0a, 0xd5, 0x7d, 0x8e, 0xb6, 0x0b, 0xe7, 0x74, 0xe4, 0x3c, 0x57, 0x34, 0x2b, 0xc6,
	0xe9, 0xad, 0x80, 0xbb, 0x65, 0x98, 0xa0, 0x40, 0xde, 0x5a, 0xc4, 0x41, 0xa7, 0x7c, 0x77, 0x3b,
	0xb3, 0xef, 0xee, 0xfa, 0xd3, 0xbd, 0x7f, 0x76, 0xe1, 0x3b, 0xe7, 0x17, 0xbe, 0xf3, 0xe7, 0xc2,
	0x77, 0xbe, 0x5d, 0xfa, 0xb5, 0xf3, 0x4b, 0xbf, 0xf6, 0xeb, 0xd2, 0xaf, 0x7d, 0x5c, 0x9b, 0xb5,
	0xaa, 0xd3, 0x9c, 0xc8, 0xe1, 0x3c, 0xfc, 0xe5, 0x3c, 0xf8, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xd6,
	0x9b, 0x0b, 0x7a, 0xca, 0x04, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ChallengePeriodBlocks != that1.ChallengePeriodBlocks {
		return false
	}
	if !this.ScalabilityParams.Equal(&that1.ScalabilityParams) {
		return false
	}
	return true
}
func (this *ScalabilityParams) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ScalabilityParams)
	if !ok {
		that2, ok := that.(ScalabilityParams)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MaxParticipantsPerShard != that1.MaxParticipantsPerShard {
		return false
	}
	if this.MaxGradientsPerBlock != that1.MaxGradientsPerBlock {
		return false
	}
	if this.MaxAggregationsPerBlock != that1.MaxAggregationsPerBlock {
		return false
	}
	if this.MaxPendingGradients != that1.MaxPendingGradients {
		return false
	}
	if this.MaxPendingAggregations != that1.MaxPendingAggregations {
		return false
	}
	if this.CompressionRatioThreshold != that1.CompressionRatioThreshold {
		return false
	}
	if this.NetworkLoadThreshold != that1.NetworkLoadThreshold {
		return false
	}
	if this.ResourceUtilizationThreshold != that1.ResourceUtilizationThreshold {
		return false
	}
	if this.EnableLoadBalancing != that1.EnableLoadBalancing {
		return false
	}
	if this.LoadBalancingStrategy != that1.LoadBalancingStrategy {
		return false
	}
	if this.ShardReassignmentInterval != that1.ShardReassignmentInterval {
		return false
	}
	if this.EnableAdaptiveCompression != that1.EnableAdaptiveCompression {
		return false
	}
	if this.EnableAdaptiveSharding != that1.EnableAdaptiveSharding {
		return false
	}
	if this.EnableResourceOptimization != that1.EnableResourceOptimization {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ScalabilityParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.ChallengePeriodBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ChallengePeriodBlocks))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ScalabilityParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScalabilityParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ScalabilityParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EnableResourceOptimization {
		i--
		if m.EnableResourceOptimization {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x70
	}
	if m.EnableAdaptiveSharding {
		i--
		if m.EnableAdaptiveSharding {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x68
	}
	if m.EnableAdaptiveCompression {
		i--
		if m.EnableAdaptiveCompression {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if m.ShardReassignmentInterval != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ShardReassignmentInterval))
		i--
		dAtA[i] = 0x58
	}
	if len(m.LoadBalancingStrategy) > 0 {
		i -= len(m.LoadBalancingStrategy)
		copy(dAtA[i:], m.LoadBalancingStrategy)
		i = encodeVarintParams(dAtA, i, uint64(len(m.LoadBalancingStrategy)))
		i--
		dAtA[i] = 0x52
	}
	if m.EnableLoadBalancing {
		i--
		if m.EnableLoadBalancing {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if len(m.ResourceUtilizationThreshold) > 0 {
		i -= len(m.ResourceUtilizationThreshold)
		copy(dAtA[i:], m.ResourceUtilizationThreshold)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ResourceUtilizationThreshold)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.NetworkLoadThreshold) > 0 {
		i -= len(m.NetworkLoadThreshold)
		copy(dAtA[i:], m.NetworkLoadThreshold)
		i = encodeVarintParams(dAtA, i, uint64(len(m.NetworkLoadThreshold)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CompressionRatioThreshold) > 0 {
		i -= len(m.CompressionRatioThreshold)
		copy(dAtA[i:], m.CompressionRatioThreshold)
		i = encodeVarintParams(dAtA, i, uint64(len(m.CompressionRatioThreshold)))
		i--
		dAtA[i] = 0x32
	}
	if m.MaxPendingAggregations != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxPendingAggregations))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxPendingGradients != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxPendingGradients))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxAggregationsPerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxAggregationsPerBlock))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxGradientsPerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxGradientsPerBlock))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxParticipantsPerShard != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxParticipantsPerShard))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChallengePeriodBlocks != 0 {
		n += 1 + sovParams(uint64(m.ChallengePeriodBlocks))
	}
	l = m.ScalabilityParams.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *ScalabilityParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxParticipantsPerShard != 0 {
		n += 1 + sovParams(uint64(m.MaxParticipantsPerShard))
	}
	if m.MaxGradientsPerBlock != 0 {
		n += 1 + sovParams(uint64(m.MaxGradientsPerBlock))
	}
	if m.MaxAggregationsPerBlock != 0 {
		n += 1 + sovParams(uint64(m.MaxAggregationsPerBlock))
	}
	if m.MaxPendingGradients != 0 {
		n += 1 + sovParams(uint64(m.MaxPendingGradients))
	}
	if m.MaxPendingAggregations != 0 {
		n += 1 + sovParams(uint64(m.MaxPendingAggregations))
	}
	l = len(m.CompressionRatioThreshold)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.NetworkLoadThreshold)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.ResourceUtilizationThreshold)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.EnableLoadBalancing {
		n += 2
	}
	l = len(m.LoadBalancingStrategy)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.ShardReassignmentInterval != 0 {
		n += 1 + sovParams(uint64(m.ShardReassignmentInterval))
	}
	if m.EnableAdaptiveCompression {
		n += 2
	}
	if m.EnableAdaptiveSharding {
		n += 2
	}
	if m.EnableResourceOptimization {
		n += 2
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengePeriodBlocks", wireType)
			}
			m.ChallengePeriodBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChallengePeriodBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScalabilityParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ScalabilityParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ScalabilityParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ScalabilityParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ScalabilityParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxParticipantsPerShard", wireType)
			}
			m.MaxParticipantsPerShard = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxParticipantsPerShard |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGradientsPerBlock", wireType)
			}
			m.MaxGradientsPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxGradientsPerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAggregationsPerBlock", wireType)
			}
			m.MaxAggregationsPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxAggregationsPerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPendingGradients", wireType)
			}
			m.MaxPendingGradients = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPendingGradients |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPendingAggregations", wireType)
			}
			m.MaxPendingAggregations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPendingAggregations |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompressionRatioThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CompressionRatioThreshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkLoadThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkLoadThreshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceUtilizationThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResourceUtilizationThreshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnableLoadBalancing", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EnableLoadBalancing = bool(v != 0)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoadBalancingStrategy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LoadBalancingStrategy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardReassignmentInterval", wireType)
			}
			m.ShardReassignmentInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardReassignmentInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnableAdaptiveCompression", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EnableAdaptiveCompression = bool(v != 0)
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnableAdaptiveSharding", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EnableAdaptiveSharding = bool(v != 0)
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnableResourceOptimization", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EnableResourceOptimization = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
