# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: remes/remes/v1/genesis.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'remes/remes/v1/genesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from remes.remes.v1 import params_pb2 as remes_dot_remes_dot_v1_dot_params__pb2
from remes.remes.v1 import stored_gradient_pb2 as remes_dot_remes_dot_v1_dot_stored__gradient__pb2
from remes.remes.v1 import model_pb2 as remes_dot_remes_dot_v1_dot_model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cremes/remes/v1/genesis.proto\x12\x0eremes.remes.v1\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\x1a\x1bremes/remes/v1/params.proto\x1a$remes/remes/v1/stored_gradient.proto\x1a\x1aremes/remes/v1/model.proto\"\xed\x02\n\x0cGenesisState\x12\x39\n\x06params\x18\x01 \x01(\x0b\x32\x16.remes.remes.v1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params\x12\x1d\n\nmodel_hash\x18\x02 \x01(\tR\tmodelHash\x12#\n\rmodel_version\x18\x03 \x01(\tR\x0cmodelVersion\x12\x31\n\x14initial_participants\x18\x04 \x03(\tR\x13initialParticipants\x12V\n\x14stored_gradient_list\x18\x05 \x03(\x0b\x32\x1e.remes.remes.v1.StoredGradientB\x04\xc8\xde\x1f\x00R\x12storedGradientList\x12S\n\x13model_registry_list\x18\x06 \x03(\x0b\x32\x1d.remes.remes.v1.ModelRegistryB\x04\xc8\xde\x1f\x00R\x11modelRegistryListB\x15Z\x13remes/x/remes/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'remes.remes.v1.genesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023remes/x/remes/types'
  _globals['_GENESISSTATE'].fields_by_name['params']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_GENESISSTATE'].fields_by_name['stored_gradient_list']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['stored_gradient_list']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['model_registry_list']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['model_registry_list']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE']._serialized_start=185
  _globals['_GENESISSTATE']._serialized_end=550
# @@protoc_insertion_point(module_scope)
