# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import query_pb2 as remes_dot_remes_dot_v1_dot_query__pb2


class QueryStub(object):
    """Query defines the gRPC querier service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Params = channel.unary_unary(
                '/remes.remes.v1.Query/Params',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryParamsRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryParamsResponse.FromString,
                _registered_method=True)
        self.GetGradient = channel.unary_unary(
                '/remes.remes.v1.Query/GetGradient',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetGradientRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetGradientResponse.FromString,
                _registered_method=True)
        self.GetModelParams = channel.unary_unary(
                '/remes.remes.v1.Query/GetModelParams',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetModelParamsRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetModelParamsResponse.FromString,
                _registered_method=True)
        self.GetAggregation = channel.unary_unary(
                '/remes.remes.v1.Query/GetAggregation',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetAggregationRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetAggregationResponse.FromString,
                _registered_method=True)
        self.GetMinerScore = channel.unary_unary(
                '/remes.remes.v1.Query/GetMinerScore',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetMinerScoreRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetMinerScoreResponse.FromString,
                _registered_method=True)
        self.ListStoredGradient = channel.unary_unary(
                '/remes.remes.v1.Query/ListStoredGradient',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListStoredGradientRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListStoredGradientResponse.FromString,
                _registered_method=True)
        self.GetStoredGradient = channel.unary_unary(
                '/remes.remes.v1.Query/GetStoredGradient',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetStoredGradientRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetStoredGradientResponse.FromString,
                _registered_method=True)
        self.GetDatasetProposal = channel.unary_unary(
                '/remes.remes.v1.Query/GetDatasetProposal',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetDatasetProposalRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetDatasetProposalResponse.FromString,
                _registered_method=True)
        self.ListDatasetProposals = channel.unary_unary(
                '/remes.remes.v1.Query/ListDatasetProposals',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListDatasetProposalsRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListDatasetProposalsResponse.FromString,
                _registered_method=True)
        self.GetApprovedDataset = channel.unary_unary(
                '/remes.remes.v1.Query/GetApprovedDataset',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetApprovedDatasetRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetApprovedDatasetResponse.FromString,
                _registered_method=True)
        self.ListApprovedDatasets = channel.unary_unary(
                '/remes.remes.v1.Query/ListApprovedDatasets',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListApprovedDatasetsRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListApprovedDatasetsResponse.FromString,
                _registered_method=True)
        self.GetNodeRegistration = channel.unary_unary(
                '/remes.remes.v1.Query/GetNodeRegistration',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetNodeRegistrationRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetNodeRegistrationResponse.FromString,
                _registered_method=True)
        self.ListNodeRegistrations = channel.unary_unary(
                '/remes.remes.v1.Query/ListNodeRegistrations',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListNodeRegistrationsRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListNodeRegistrationsResponse.FromString,
                _registered_method=True)
        self.GetInferenceRequest = channel.unary_unary(
                '/remes.remes.v1.Query/GetInferenceRequest',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetInferenceRequestRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetInferenceRequestResponse.FromString,
                _registered_method=True)
        self.GetServingNodeStatus = channel.unary_unary(
                '/remes.remes.v1.Query/GetServingNodeStatus',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetServingNodeStatusRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetServingNodeStatusResponse.FromString,
                _registered_method=True)
        self.ListServingNodes = channel.unary_unary(
                '/remes.remes.v1.Query/ListServingNodes',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListServingNodesRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListServingNodesResponse.FromString,
                _registered_method=True)
        self.GetRewardFormula = channel.unary_unary(
                '/remes.remes.v1.Query/GetRewardFormula',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetRewardFormulaRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetRewardFormulaResponse.FromString,
                _registered_method=True)
        self.GetParticipantSyncState = channel.unary_unary(
                '/remes.remes.v1.Query/GetParticipantSyncState',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetParticipantSyncStateRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetParticipantSyncStateResponse.FromString,
                _registered_method=True)
        self.ListParticipantSyncStates = channel.unary_unary(
                '/remes.remes.v1.Query/ListParticipantSyncStates',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListParticipantSyncStatesRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListParticipantSyncStatesResponse.FromString,
                _registered_method=True)
        self.GetGlobalModelState = channel.unary_unary(
                '/remes.remes.v1.Query/GetGlobalModelState',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetGlobalModelStateRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetGlobalModelStateResponse.FromString,
                _registered_method=True)
        self.GetCatchUpInfo = channel.unary_unary(
                '/remes.remes.v1.Query/GetCatchUpInfo',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetCatchUpInfoRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetCatchUpInfoResponse.FromString,
                _registered_method=True)
        self.GetGlobalSeed = channel.unary_unary(
                '/remes.remes.v1.Query/GetGlobalSeed',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetGlobalSeedRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetGlobalSeedResponse.FromString,
                _registered_method=True)
        self.QueryMiners = channel.unary_unary(
                '/remes.remes.v1.Query/QueryMiners',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryMinersRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryMinersResponse.FromString,
                _registered_method=True)
        self.QueryStatistics = channel.unary_unary(
                '/remes.remes.v1.Query/QueryStatistics',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryStatisticsRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryStatisticsResponse.FromString,
                _registered_method=True)
        self.QueryBlocks = channel.unary_unary(
                '/remes.remes.v1.Query/QueryBlocks',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryBlocksRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryBlocksResponse.FromString,
                _registered_method=True)
        self.QueryBlock = channel.unary_unary(
                '/remes.remes.v1.Query/QueryBlock',
                request_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryBlockRequest.SerializeToString,
                response_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryBlockResponse.FromString,
                _registered_method=True)


class QueryServicer(object):
    """Query defines the gRPC querier service.
    """

    def Params(self, request, context):
        """Parameters queries the parameters of the module.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGradient(self, request, context):
        """GetGradient queries a specific gradient by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelParams(self, request, context):
        """GetModelParams queries the current global model parameters (IPFS hash)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAggregation(self, request, context):
        """GetAggregation queries a specific aggregation by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMinerScore(self, request, context):
        """GetMinerScore queries the reputation score and statistics for a miner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStoredGradient(self, request, context):
        """ListStoredGradient queries all stored gradients with pagination
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStoredGradient(self, request, context):
        """GetStoredGradient queries a specific stored gradient by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatasetProposal(self, request, context):
        """GetDatasetProposal queries a dataset proposal by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatasetProposals(self, request, context):
        """ListDatasetProposals lists all dataset proposals
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApprovedDataset(self, request, context):
        """GetApprovedDataset queries an approved dataset by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApprovedDatasets(self, request, context):
        """ListApprovedDatasets lists all approved datasets
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeRegistration(self, request, context):
        """GetNodeRegistration queries a node registration by address
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodeRegistrations(self, request, context):
        """ListNodeRegistrations lists all node registrations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInferenceRequest(self, request, context):
        """GetInferenceRequest queries an inference request by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServingNodeStatus(self, request, context):
        """GetServingNodeStatus queries serving node status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServingNodes(self, request, context):
        """ListServingNodes lists all serving nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRewardFormula(self, request, context):
        """GetRewardFormula queries transparent reward formulas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParticipantSyncState(self, request, context):
        """GetParticipantSyncState queries a participant's synchronization state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListParticipantSyncStates(self, request, context):
        """ListParticipantSyncStates lists all participant sync states with pagination
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGlobalModelState(self, request, context):
        """GetGlobalModelState queries the current global model state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCatchUpInfo(self, request, context):
        """GetCatchUpInfo returns information needed for a participant to catch up after network partition
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGlobalSeed(self, request, context):
        """GetGlobalSeed returns the global seed for a training round
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryMiners(self, request, context):
        """QueryMiners queries all miners with pagination (for dashboard API)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryStatistics(self, request, context):
        """QueryStatistics queries network statistics (for dashboard API)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryBlocks(self, request, context):
        """QueryBlocks queries recent blocks with pagination (for dashboard API)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryBlock(self, request, context):
        """QueryBlock queries a specific block by height (for dashboard API)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Params': grpc.unary_unary_rpc_method_handler(
                    servicer.Params,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryParamsRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryParamsResponse.SerializeToString,
            ),
            'GetGradient': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGradient,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetGradientRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetGradientResponse.SerializeToString,
            ),
            'GetModelParams': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelParams,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetModelParamsRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetModelParamsResponse.SerializeToString,
            ),
            'GetAggregation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAggregation,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetAggregationRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetAggregationResponse.SerializeToString,
            ),
            'GetMinerScore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMinerScore,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetMinerScoreRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetMinerScoreResponse.SerializeToString,
            ),
            'ListStoredGradient': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStoredGradient,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListStoredGradientRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListStoredGradientResponse.SerializeToString,
            ),
            'GetStoredGradient': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStoredGradient,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetStoredGradientRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetStoredGradientResponse.SerializeToString,
            ),
            'GetDatasetProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatasetProposal,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetDatasetProposalRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetDatasetProposalResponse.SerializeToString,
            ),
            'ListDatasetProposals': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatasetProposals,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListDatasetProposalsRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListDatasetProposalsResponse.SerializeToString,
            ),
            'GetApprovedDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApprovedDataset,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetApprovedDatasetRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetApprovedDatasetResponse.SerializeToString,
            ),
            'ListApprovedDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApprovedDatasets,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListApprovedDatasetsRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListApprovedDatasetsResponse.SerializeToString,
            ),
            'GetNodeRegistration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeRegistration,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetNodeRegistrationRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetNodeRegistrationResponse.SerializeToString,
            ),
            'ListNodeRegistrations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodeRegistrations,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListNodeRegistrationsRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListNodeRegistrationsResponse.SerializeToString,
            ),
            'GetInferenceRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInferenceRequest,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetInferenceRequestRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetInferenceRequestResponse.SerializeToString,
            ),
            'GetServingNodeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServingNodeStatus,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetServingNodeStatusRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetServingNodeStatusResponse.SerializeToString,
            ),
            'ListServingNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServingNodes,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListServingNodesRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListServingNodesResponse.SerializeToString,
            ),
            'GetRewardFormula': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRewardFormula,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetRewardFormulaRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetRewardFormulaResponse.SerializeToString,
            ),
            'GetParticipantSyncState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParticipantSyncState,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetParticipantSyncStateRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetParticipantSyncStateResponse.SerializeToString,
            ),
            'ListParticipantSyncStates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListParticipantSyncStates,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListParticipantSyncStatesRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryListParticipantSyncStatesResponse.SerializeToString,
            ),
            'GetGlobalModelState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalModelState,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetGlobalModelStateRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetGlobalModelStateResponse.SerializeToString,
            ),
            'GetCatchUpInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCatchUpInfo,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetCatchUpInfoRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetCatchUpInfoResponse.SerializeToString,
            ),
            'GetGlobalSeed': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalSeed,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetGlobalSeedRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryGetGlobalSeedResponse.SerializeToString,
            ),
            'QueryMiners': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryMiners,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryMinersRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryMinersResponse.SerializeToString,
            ),
            'QueryStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryStatistics,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryStatisticsRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryStatisticsResponse.SerializeToString,
            ),
            'QueryBlocks': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryBlocks,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryBlocksRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryBlocksResponse.SerializeToString,
            ),
            'QueryBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryBlock,
                    request_deserializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryBlockRequest.FromString,
                    response_serializer=remes_dot_remes_dot_v1_dot_query__pb2.QueryBlockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'remes.remes.v1.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('remes.remes.v1.Query', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Query(object):
    """Query defines the gRPC querier service.
    """

    @staticmethod
    def Params(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/Params',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryParamsRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGradient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/GetGradient',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetGradientRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetGradientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/GetModelParams',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetModelParamsRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetModelParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAggregation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/GetAggregation',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetAggregationRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetAggregationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMinerScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/GetMinerScore',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetMinerScoreRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetMinerScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStoredGradient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/ListStoredGradient',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryListStoredGradientRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryListStoredGradientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStoredGradient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/GetStoredGradient',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetStoredGradientRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetStoredGradientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDatasetProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/GetDatasetProposal',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetDatasetProposalRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetDatasetProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDatasetProposals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/ListDatasetProposals',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryListDatasetProposalsRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryListDatasetProposalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetApprovedDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/GetApprovedDataset',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetApprovedDatasetRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetApprovedDatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApprovedDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/ListApprovedDatasets',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryListApprovedDatasetsRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryListApprovedDatasetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeRegistration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/GetNodeRegistration',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetNodeRegistrationRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetNodeRegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodeRegistrations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/ListNodeRegistrations',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryListNodeRegistrationsRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryListNodeRegistrationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInferenceRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/GetInferenceRequest',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetInferenceRequestRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetInferenceRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServingNodeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/GetServingNodeStatus',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetServingNodeStatusRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetServingNodeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServingNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/ListServingNodes',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryListServingNodesRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryListServingNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRewardFormula(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/GetRewardFormula',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetRewardFormulaRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetRewardFormulaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParticipantSyncState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/GetParticipantSyncState',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetParticipantSyncStateRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetParticipantSyncStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListParticipantSyncStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/ListParticipantSyncStates',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryListParticipantSyncStatesRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryListParticipantSyncStatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGlobalModelState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/GetGlobalModelState',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetGlobalModelStateRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetGlobalModelStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCatchUpInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/GetCatchUpInfo',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetCatchUpInfoRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetCatchUpInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGlobalSeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/GetGlobalSeed',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetGlobalSeedRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryGetGlobalSeedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryMiners(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/QueryMiners',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryMinersRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryMinersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/QueryStatistics',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryStatisticsRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryStatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/QueryBlocks',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryBlocksRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryBlocksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remes.remes.v1.Query/QueryBlock',
            remes_dot_remes_dot_v1_dot_query__pb2.QueryBlockRequest.SerializeToString,
            remes_dot_remes_dot_v1_dot_query__pb2.QueryBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
