# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: remes/remes/v1/serving.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'remes/remes/v1/serving.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cremes/remes/v1/serving.proto\x12\x0eremes.remes.v1\x1a\x14gogoproto/gogo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcb\x03\n\x10InferenceRequest\x12\x1d\n\nrequest_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n\trequester\x18\x02 \x01(\tR\trequester\x12!\n\x0cserving_node\x18\x03 \x01(\tR\x0bservingNode\x12#\n\rmodel_version\x18\x04 \x01(\tR\x0cmodelVersion\x12/\n\x14input_data_ipfs_hash\x18\x05 \x01(\tR\x11inputDataIpfsHash\x12\x10\n\x03\x66\x65\x65\x18\x06 \x01(\tR\x03\x66\x65\x65\x12G\n\x0crequest_time\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x08\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\x0brequestTime\x12\x45\n\rresponse_time\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x04\x90\xdf\x1f\x01R\x0cresponseTime\x12(\n\x10result_ipfs_hash\x18\t \x01(\tR\x0eresultIpfsHash\x12\x16\n\x06status\x18\n \x01(\tR\x06status\x12\x1d\n\nlatency_ms\x18\x0b \x01(\x04R\tlatencyMs\"\xf9\x02\n\x11ServingNodeStatus\x12!\n\x0cnode_address\x18\x01 \x01(\tR\x0bnodeAddress\x12#\n\rmodel_version\x18\x02 \x01(\tR\x0cmodelVersion\x12&\n\x0fmodel_ipfs_hash\x18\x03 \x01(\tR\rmodelIpfsHash\x12!\n\x0cis_available\x18\x04 \x01(\x08R\x0bisAvailable\x12%\n\x0etotal_requests\x18\x05 \x01(\x04R\rtotalRequests\x12/\n\x13successful_requests\x18\x06 \x01(\x04R\x12successfulRequests\x12,\n\x12\x61verage_latency_ms\x18\x07 \x01(\x04R\x10\x61verageLatencyMs\x12K\n\x0elast_heartbeat\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x08\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\rlastHeartbeatB\x15Z\x13remes/x/remes/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'remes.remes.v1.serving_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023remes/x/remes/types'
  _globals['_INFERENCEREQUEST'].fields_by_name['request_time']._loaded_options = None
  _globals['_INFERENCEREQUEST'].fields_by_name['request_time']._serialized_options = b'\310\336\037\000\220\337\037\001'
  _globals['_INFERENCEREQUEST'].fields_by_name['response_time']._loaded_options = None
  _globals['_INFERENCEREQUEST'].fields_by_name['response_time']._serialized_options = b'\220\337\037\001'
  _globals['_SERVINGNODESTATUS'].fields_by_name['last_heartbeat']._loaded_options = None
  _globals['_SERVINGNODESTATUS'].fields_by_name['last_heartbeat']._serialized_options = b'\310\336\037\000\220\337\037\001'
  _globals['_INFERENCEREQUEST']._serialized_start=104
  _globals['_INFERENCEREQUEST']._serialized_end=563
  _globals['_SERVINGNODESTATUS']._serialized_start=566
  _globals['_SERVINGNODESTATUS']._serialized_end=943
# @@protoc_insertion_point(module_scope)
