# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: remes/remes/v1/verification.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'remes/remes/v1/verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!remes/remes/v1/verification.proto\x12\x0eremes.remes.v1\"\xdb\x01\n\x15RunForwardPassRequest\x12*\n\x11weights_ipfs_hash\x18\x01 \x01(\tR\x0fweightsIpfsHash\x12\x19\n\x08\x62\x61tch_id\x18\x02 \x01(\tR\x07\x62\x61tchId\x12&\n\x0fmodel_config_id\x18\x03 \x01(\x04R\rmodelConfigId\x12*\n\x11\x64\x61taset_ipfs_hash\x18\x04 \x01(\tR\x0f\x64\x61tasetIpfsHash\x12\'\n\x0ftimeout_seconds\x18\x05 \x01(\rR\x0etimeoutSeconds\"\xb9\x01\n\x16RunForwardPassResponse\x12\x19\n\x08loss_int\x18\x01 \x01(\x03R\x07lossInt\x12\x18\n\x07success\x18\x02 \x01(\x08R\x07success\x12#\n\rerror_message\x18\x03 \x01(\tR\x0c\x65rrorMessage\x12*\n\x11\x65xecution_time_ms\x18\x04 \x01(\x04R\x0f\x65xecutionTimeMs\x12\x19\n\x08gpu_info\x18\x05 \x01(\tR\x07gpuInfo\"\x14\n\x12HealthCheckRequest\"\x93\x01\n\x13HealthCheckResponse\x12\x18\n\x07healthy\x18\x01 \x01(\x08R\x07healthy\x12\x18\n\x07version\x18\x02 \x01(\tR\x07version\x12%\n\x0e\x61vailable_gpus\x18\x03 \x03(\tR\ravailableGpus\x12!\n\x0cmodel_loaded\x18\x04 \x01(\x08R\x0bmodelLoaded2\xce\x01\n\x13VerificationService\x12_\n\x0eRunForwardPass\x12%.remes.remes.v1.RunForwardPassRequest\x1a&.remes.remes.v1.RunForwardPassResponse\x12V\n\x0bHealthCheck\x12\".remes.remes.v1.HealthCheckRequest\x1a#.remes.remes.v1.HealthCheckResponseB(Z&github.com/remesio/remes/x/remes/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'remes.remes.v1.verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/remesio/remes/x/remes/types'
  _globals['_RUNFORWARDPASSREQUEST']._serialized_start=54
  _globals['_RUNFORWARDPASSREQUEST']._serialized_end=273
  _globals['_RUNFORWARDPASSRESPONSE']._serialized_start=276
  _globals['_RUNFORWARDPASSRESPONSE']._serialized_end=461
  _globals['_HEALTHCHECKREQUEST']._serialized_start=463
  _globals['_HEALTHCHECKREQUEST']._serialized_end=483
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=486
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=633
  _globals['_VERIFICATIONSERVICE']._serialized_start=636
  _globals['_VERIFICATIONSERVICE']._serialized_end=842
# @@protoc_insertion_point(module_scope)
