#!/bin/bash
# Start Debug Mode Script
# Sets up environment variables and starts R3MES components in debug mode

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Default debug settings
DEBUG_MODE="${R3MES_DEBUG_MODE:-true}"
DEBUG_LEVEL="${R3MES_DEBUG_LEVEL:-verbose}"
DEBUG_COMPONENTS="${R3MES_DEBUG_COMPONENTS:-blockchain,backend,miner,launcher,frontend}"
DEBUG_LOGGING="${R3MES_DEBUG_LOGGING:-true}"
DEBUG_PROFILING="${R3MES_DEBUG_PROFILING:-true}"
DEBUG_STATE_INSPECTION="${R3MES_DEBUG_STATE_INSPECTION:-true}"
DEBUG_TRACE="${R3MES_DEBUG_TRACE:-true}"
DEBUG_LOG_LEVEL="${R3MES_DEBUG_LOG_LEVEL:-TRACE}"
DEBUG_LOG_FORMAT="${R3MES_DEBUG_LOG_FORMAT:-json}"

# Create debug directories
DEBUG_DIR="$HOME/.r3mes"
mkdir -p "$DEBUG_DIR/logs"
mkdir -p "$DEBUG_DIR/profiles"
mkdir -p "$DEBUG_DIR/traces"

echo "========================================="
echo "R3MES Debug Mode Startup"
echo "========================================="
echo "Project Root: $PROJECT_ROOT"
echo "Debug Directory: $DEBUG_DIR"
echo ""
echo "Debug Configuration:"
echo "  Mode: $DEBUG_MODE"
echo "  Level: $DEBUG_LEVEL"
echo "  Components: $DEBUG_COMPONENTS"
echo "  Logging: $DEBUG_LOGGING"
echo "  Profiling: $DEBUG_PROFILING"
echo "  State Inspection: $DEBUG_STATE_INSPECTION"
echo "  Trace: $DEBUG_TRACE"
echo "  Log Level: $DEBUG_LOG_LEVEL"
echo "  Log Format: $DEBUG_LOG_FORMAT"
echo "========================================="
echo ""

# Export environment variables
export R3MES_DEBUG_MODE="$DEBUG_MODE"
export R3MES_DEBUG_LEVEL="$DEBUG_LEVEL"
export R3MES_DEBUG_COMPONENTS="$DEBUG_COMPONENTS"
export R3MES_DEBUG_LOGGING="$DEBUG_LOGGING"
export R3MES_DEBUG_PROFILING="$DEBUG_PROFILING"
export R3MES_DEBUG_STATE_INSPECTION="$DEBUG_STATE_INSPECTION"
export R3MES_DEBUG_TRACE="$DEBUG_TRACE"
export R3MES_DEBUG_LOG_LEVEL="$DEBUG_LOG_LEVEL"
export R3MES_DEBUG_LOG_FORMAT="$DEBUG_LOG_FORMAT"
export R3MES_DEBUG_LOG_FILE="$DEBUG_DIR/debug.log"
export R3MES_DEBUG_PROFILE_OUTPUT="$DEBUG_DIR/profiles"
export R3MES_DEBUG_TRACE_EXPORT_PATH="$DEBUG_DIR/traces"
export R3MES_DEBUG_TRACE_ENABLED="$DEBUG_TRACE"
export R3MES_DEBUG_TRACE_BUFFER_SIZE="10000"
export R3MES_DEBUG_PROFILE_INTERVAL="60"

echo "Environment variables set. You can now start R3MES components."
echo ""
echo "To start components:"
echo "  - Blockchain: cd $PROJECT_ROOT/remes && make install && remesd start"
echo "  - Backend: cd $PROJECT_ROOT/backend && python3 -m app.main"
echo "  - Miner: cd $PROJECT_ROOT/miner-engine && python3 miner_engine.py"
echo ""
echo "Debug logs will be written to: $DEBUG_DIR/debug.log"
echo "Profiles will be written to: $DEBUG_DIR/profiles/"
echo "Traces will be written to: $DEBUG_DIR/traces/"
echo ""
echo "To stop debug mode, unset R3MES_DEBUG_MODE or run:"
echo "  unset R3MES_DEBUG_MODE"
echo ""
