// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: remes/remes/v1/task_pool.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// TaskPool represents an open buffet task pool with multiple chunks
type TaskPool struct {
	// pool_id is the unique identifier for this task pool
	PoolId uint64 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	// window_id is the training window identifier
	WindowId uint64 `protobuf:"varint,2,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	// total_chunks is the total number of chunks in this pool (e.g., 50 chunks per block)
	TotalChunks uint64 `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	// available_chunks is the list of available chunks
	AvailableChunks []TaskChunk `protobuf:"bytes,4,rep,name=available_chunks,json=availableChunks,proto3" json:"available_chunks"`
	// completed_chunks is the list of IPFS hashes of completed tasks
	CompletedChunks []string `protobuf:"bytes,5,rep,name=completed_chunks,json=completedChunks,proto3" json:"completed_chunks,omitempty"`
	// status is the current status of the pool ("active", "aggregating", "closed")
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// created_height is the block height when this pool was created
	CreatedHeight int64 `protobuf:"varint,7,opt,name=created_height,json=createdHeight,proto3" json:"created_height,omitempty"`
	// expiry_height is the block height when this pool expires (window closes after N blocks)
	ExpiryHeight int64 `protobuf:"varint,8,opt,name=expiry_height,json=expiryHeight,proto3" json:"expiry_height,omitempty"`
}

func (m *TaskPool) Reset()         { *m = TaskPool{} }
func (m *TaskPool) String() string { return proto.CompactTextString(m) }
func (*TaskPool) ProtoMessage()    {}
func (*TaskPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_839decc3f9aaef98, []int{0}
}
func (m *TaskPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TaskPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TaskPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TaskPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskPool.Merge(m, src)
}
func (m *TaskPool) XXX_Size() int {
	return m.Size()
}
func (m *TaskPool) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskPool.DiscardUnknown(m)
}

var xxx_messageInfo_TaskPool proto.InternalMessageInfo

func (m *TaskPool) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *TaskPool) GetWindowId() uint64 {
	if m != nil {
		return m.WindowId
	}
	return 0
}

func (m *TaskPool) GetTotalChunks() uint64 {
	if m != nil {
		return m.TotalChunks
	}
	return 0
}

func (m *TaskPool) GetAvailableChunks() []TaskChunk {
	if m != nil {
		return m.AvailableChunks
	}
	return nil
}

func (m *TaskPool) GetCompletedChunks() []string {
	if m != nil {
		return m.CompletedChunks
	}
	return nil
}

func (m *TaskPool) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TaskPool) GetCreatedHeight() int64 {
	if m != nil {
		return m.CreatedHeight
	}
	return 0
}

func (m *TaskPool) GetExpiryHeight() int64 {
	if m != nil {
		return m.ExpiryHeight
	}
	return 0
}

// TaskChunk represents a single chunk in the task pool
type TaskChunk struct {
	// chunk_id is the unique identifier for this chunk
	ChunkId uint64 `protobuf:"varint,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	// data_hash is the IPFS hash of chunk data
	DataHash string `protobuf:"bytes,2,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	// shard_id is the shard identifier
	ShardId uint64 `protobuf:"varint,3,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// assigned_miner is the miner address assigned to this chunk (optional, can be empty for open pool)
	AssignedMiner string `protobuf:"bytes,4,opt,name=assigned_miner,json=assignedMiner,proto3" json:"assigned_miner,omitempty"`
	// status is the current status of the chunk ("available", "in_progress", "completed")
	Status string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// claimed_at is the timestamp when this chunk was claimed
	ClaimedAt int64 `protobuf:"varint,6,opt,name=claimed_at,json=claimedAt,proto3" json:"claimed_at,omitempty"`
	// completed_at is the timestamp when this chunk was completed
	CompletedAt int64 `protobuf:"varint,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// gradient_hash is the IPFS hash of the result gradient
	GradientHash string `protobuf:"bytes,8,opt,name=gradient_hash,json=gradientHash,proto3" json:"gradient_hash,omitempty"`
}

func (m *TaskChunk) Reset()         { *m = TaskChunk{} }
func (m *TaskChunk) String() string { return proto.CompactTextString(m) }
func (*TaskChunk) ProtoMessage()    {}
func (*TaskChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_839decc3f9aaef98, []int{1}
}
func (m *TaskChunk) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TaskChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TaskChunk.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TaskChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskChunk.Merge(m, src)
}
func (m *TaskChunk) XXX_Size() int {
	return m.Size()
}
func (m *TaskChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskChunk.DiscardUnknown(m)
}

var xxx_messageInfo_TaskChunk proto.InternalMessageInfo

func (m *TaskChunk) GetChunkId() uint64 {
	if m != nil {
		return m.ChunkId
	}
	return 0
}

func (m *TaskChunk) GetDataHash() string {
	if m != nil {
		return m.DataHash
	}
	return ""
}

func (m *TaskChunk) GetShardId() uint64 {
	if m != nil {
		return m.ShardId
	}
	return 0
}

func (m *TaskChunk) GetAssignedMiner() string {
	if m != nil {
		return m.AssignedMiner
	}
	return ""
}

func (m *TaskChunk) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TaskChunk) GetClaimedAt() int64 {
	if m != nil {
		return m.ClaimedAt
	}
	return 0
}

func (m *TaskChunk) GetCompletedAt() int64 {
	if m != nil {
		return m.CompletedAt
	}
	return 0
}

func (m *TaskChunk) GetGradientHash() string {
	if m != nil {
		return m.GradientHash
	}
	return ""
}

func init() {
	proto.RegisterType((*TaskPool)(nil), "remes.remes.v1.TaskPool")
	proto.RegisterType((*TaskChunk)(nil), "remes.remes.v1.TaskChunk")
}

func init() { proto.RegisterFile("remes/remes/v1/task_pool.proto", fileDescriptor_839decc3f9aaef98) }

var fileDescriptor_839decc3f9aaef98 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xe3, 0x24, 0x4d, 0xec, 0x4d, 0xd2, 0x16, 0x83, 0xda, 0xb4, 0x08, 0xc7, 0x14, 0x21,
	0x19, 0x24, 0x12, 0x15, 0x6e, 0xbd, 0x15, 0x2e, 0x0d, 0x12, 0x12, 0xb2, 0x38, 0x71, 0xb1, 0xa6,
	0xd9, 0x95, 0xbd, 0x8a, 0xed, 0xb5, 0xbc, 0xdb, 0xb4, 0x7d, 0x05, 0x4e, 0x3c, 0x02, 0x27, 0xce,
	0x3c, 0x46, 0x8f, 0x3d, 0x72, 0x02, 0x94, 0x1c, 0xe0, 0x31, 0xd0, 0xce, 0xda, 0x29, 0x11, 0x97,
	0xd5, 0xce, 0x37, 0xf3, 0x8f, 0x67, 0xff, 0x31, 0xf1, 0x4a, 0x96, 0x31, 0x39, 0x31, 0xe7, 0xe2,
	0x78, 0xa2, 0x40, 0xce, 0xa3, 0x42, 0x88, 0x74, 0x5c, 0x94, 0x42, 0x09, 0x77, 0x1b, 0x33, 0x63,
	0x73, 0x2e, 0x8e, 0x0f, 0xef, 0x41, 0xc6, 0x73, 0x31, 0xc1, 0xd3, 0x94, 0x1c, 0x3e, 0x88, 0x45,
	0x2c, 0xf0, 0x3a, 0xd1, 0x37, 0x43, 0x8f, 0x7e, 0x36, 0x89, 0xfd, 0x01, 0xe4, 0xfc, 0xbd, 0x10,
	0xa9, 0xbb, 0x4f, 0xba, 0xba, 0x67, 0xc4, 0xe9, 0xd0, 0xf2, 0xad, 0xa0, 0x1d, 0x76, 0x74, 0x38,
	0xa5, 0xee, 0x43, 0xe2, 0x5c, 0xf2, 0x9c, 0x8a, 0x4b, 0x9d, 0x6a, 0x62, 0xca, 0x36, 0x60, 0x4a,
	0xdd, 0xc7, 0xa4, 0xaf, 0x84, 0x82, 0x34, 0x9a, 0x25, 0x17, 0xf9, 0x5c, 0x0e, 0x5b, 0x98, 0xef,
	0x21, 0x7b, 0x83, 0xc8, 0x7d, 0x4b, 0x76, 0x61, 0x01, 0x3c, 0x85, 0xf3, 0x94, 0xd5, 0x65, 0x6d,
	0xbf, 0x15, 0xf4, 0x5e, 0x1e, 0x8c, 0x37, 0x27, 0x1f, 0xeb, 0x61, 0x50, 0xf5, 0xba, 0x7d, 0xf3,
	0x63, 0xd4, 0x08, 0x77, 0xd6, 0xc2, 0xaa, 0xd7, 0x33, 0xb2, 0x3b, 0x13, 0x59, 0x91, 0x32, 0xc5,
	0x68, 0xdd, 0x6b, 0xcb, 0x6f, 0x05, 0x4e, 0xb8, 0xb3, 0xe6, 0x55, 0xe9, 0x1e, 0xe9, 0x48, 0x05,
	0xea, 0x42, 0x0e, 0x3b, 0xbe, 0x15, 0x38, 0x61, 0x15, 0xb9, 0x4f, 0xc9, 0xf6, 0xac, 0x64, 0xa0,
	0x1b, 0x24, 0x8c, 0xc7, 0x89, 0x1a, 0x76, 0x7d, 0x2b, 0x68, 0x85, 0x83, 0x8a, 0x9e, 0x21, 0x74,
	0x9f, 0x90, 0x01, 0xbb, 0x2a, 0x78, 0x79, 0x5d, 0x57, 0xd9, 0x58, 0xd5, 0x37, 0xd0, 0x14, 0x9d,
	0x8c, 0xfe, 0x7c, 0x19, 0x59, 0x9f, 0x7e, 0x7f, 0x7b, 0xbe, 0x67, 0x96, 0x73, 0x55, 0x2d, 0xa9,
	0x36, 0xf5, 0xe8, 0x6b, 0x93, 0x38, 0xeb, 0x47, 0xb9, 0x07, 0xc4, 0xc6, 0x99, 0xef, 0x3c, 0xee,
	0x62, 0x6c, 0x4c, 0xa6, 0xa0, 0x20, 0x4a, 0x40, 0x26, 0x68, 0xb2, 0x13, 0xda, 0x1a, 0x9c, 0x81,
	0x4c, 0xb4, 0x4e, 0x26, 0x50, 0x52, 0xad, 0x33, 0x06, 0x77, 0x31, 0x9e, 0x52, 0xfd, 0x1a, 0x90,
	0x92, 0xc7, 0x39, 0xa3, 0x51, 0xc6, 0x73, 0x56, 0x0e, 0xdb, 0x28, 0x1e, 0xd4, 0xf4, 0x9d, 0x86,
	0xff, 0x98, 0xb1, 0xb5, 0x61, 0xc6, 0x23, 0x42, 0x66, 0x29, 0xf0, 0x8c, 0xd1, 0x08, 0x14, 0x1a,
	0xd5, 0x0a, 0x9d, 0x8a, 0x9c, 0x2a, 0xbd, 0xdd, 0x3b, 0xbb, 0xa1, 0x76, 0xaa, 0xb7, 0x66, 0xa7,
	0xe8, 0x53, 0x5c, 0x02, 0xe5, 0x2c, 0x57, 0x66, 0x78, 0x1b, 0x3f, 0xd0, 0xaf, 0xa1, 0x7e, 0xc0,
	0x89, 0x5f, 0xfb, 0xb4, 0xff, 0xbf, 0x4f, 0x66, 0xdf, 0x2f, 0x6e, 0x96, 0x9e, 0x75, 0xbb, 0xf4,
	0xac, 0x5f, 0x4b, 0xcf, 0xfa, 0xbc, 0xf2, 0x1a, 0xb7, 0x2b, 0xaf, 0xf1, 0x7d, 0xe5, 0x35, 0x3e,
	0xde, 0xdf, 0x94, 0xa8, 0xeb, 0x82, 0xc9, 0xf3, 0x0e, 0xfe, 0xc0, 0xaf, 0xfe, 0x06, 0x00, 0x00,
	0xff, 0xff, 0x1b, 0x68, 0x66, 0x8a, 0x1b, 0x03, 0x00, 0x00,
}

func (this *TaskPool) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TaskPool)
	if !ok {
		that2, ok := that.(TaskPool)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.PoolId != that1.PoolId {
		return false
	}
	if this.WindowId != that1.WindowId {
		return false
	}
	if this.TotalChunks != that1.TotalChunks {
		return false
	}
	if len(this.AvailableChunks) != len(that1.AvailableChunks) {
		return false
	}
	for i := range this.AvailableChunks {
		if !this.AvailableChunks[i].Equal(&that1.AvailableChunks[i]) {
			return false
		}
	}
	if len(this.CompletedChunks) != len(that1.CompletedChunks) {
		return false
	}
	for i := range this.CompletedChunks {
		if this.CompletedChunks[i] != that1.CompletedChunks[i] {
			return false
		}
	}
	if this.Status != that1.Status {
		return false
	}
	if this.CreatedHeight != that1.CreatedHeight {
		return false
	}
	if this.ExpiryHeight != that1.ExpiryHeight {
		return false
	}
	return true
}
func (this *TaskChunk) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TaskChunk)
	if !ok {
		that2, ok := that.(TaskChunk)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ChunkId != that1.ChunkId {
		return false
	}
	if this.DataHash != that1.DataHash {
		return false
	}
	if this.ShardId != that1.ShardId {
		return false
	}
	if this.AssignedMiner != that1.AssignedMiner {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if this.ClaimedAt != that1.ClaimedAt {
		return false
	}
	if this.CompletedAt != that1.CompletedAt {
		return false
	}
	if this.GradientHash != that1.GradientHash {
		return false
	}
	return true
}
func (m *TaskPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaskPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TaskPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpiryHeight != 0 {
		i = encodeVarintTaskPool(dAtA, i, uint64(m.ExpiryHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.CreatedHeight != 0 {
		i = encodeVarintTaskPool(dAtA, i, uint64(m.CreatedHeight))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintTaskPool(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.CompletedChunks) > 0 {
		for iNdEx := len(m.CompletedChunks) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.CompletedChunks[iNdEx])
			copy(dAtA[i:], m.CompletedChunks[iNdEx])
			i = encodeVarintTaskPool(dAtA, i, uint64(len(m.CompletedChunks[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.AvailableChunks) > 0 {
		for iNdEx := len(m.AvailableChunks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AvailableChunks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTaskPool(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.TotalChunks != 0 {
		i = encodeVarintTaskPool(dAtA, i, uint64(m.TotalChunks))
		i--
		dAtA[i] = 0x18
	}
	if m.WindowId != 0 {
		i = encodeVarintTaskPool(dAtA, i, uint64(m.WindowId))
		i--
		dAtA[i] = 0x10
	}
	if m.PoolId != 0 {
		i = encodeVarintTaskPool(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *TaskChunk) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaskChunk) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TaskChunk) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GradientHash) > 0 {
		i -= len(m.GradientHash)
		copy(dAtA[i:], m.GradientHash)
		i = encodeVarintTaskPool(dAtA, i, uint64(len(m.GradientHash)))
		i--
		dAtA[i] = 0x42
	}
	if m.CompletedAt != 0 {
		i = encodeVarintTaskPool(dAtA, i, uint64(m.CompletedAt))
		i--
		dAtA[i] = 0x38
	}
	if m.ClaimedAt != 0 {
		i = encodeVarintTaskPool(dAtA, i, uint64(m.ClaimedAt))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintTaskPool(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.AssignedMiner) > 0 {
		i -= len(m.AssignedMiner)
		copy(dAtA[i:], m.AssignedMiner)
		i = encodeVarintTaskPool(dAtA, i, uint64(len(m.AssignedMiner)))
		i--
		dAtA[i] = 0x22
	}
	if m.ShardId != 0 {
		i = encodeVarintTaskPool(dAtA, i, uint64(m.ShardId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.DataHash) > 0 {
		i -= len(m.DataHash)
		copy(dAtA[i:], m.DataHash)
		i = encodeVarintTaskPool(dAtA, i, uint64(len(m.DataHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.ChunkId != 0 {
		i = encodeVarintTaskPool(dAtA, i, uint64(m.ChunkId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTaskPool(dAtA []byte, offset int, v uint64) int {
	offset -= sovTaskPool(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TaskPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolId != 0 {
		n += 1 + sovTaskPool(uint64(m.PoolId))
	}
	if m.WindowId != 0 {
		n += 1 + sovTaskPool(uint64(m.WindowId))
	}
	if m.TotalChunks != 0 {
		n += 1 + sovTaskPool(uint64(m.TotalChunks))
	}
	if len(m.AvailableChunks) > 0 {
		for _, e := range m.AvailableChunks {
			l = e.Size()
			n += 1 + l + sovTaskPool(uint64(l))
		}
	}
	if len(m.CompletedChunks) > 0 {
		for _, s := range m.CompletedChunks {
			l = len(s)
			n += 1 + l + sovTaskPool(uint64(l))
		}
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovTaskPool(uint64(l))
	}
	if m.CreatedHeight != 0 {
		n += 1 + sovTaskPool(uint64(m.CreatedHeight))
	}
	if m.ExpiryHeight != 0 {
		n += 1 + sovTaskPool(uint64(m.ExpiryHeight))
	}
	return n
}

func (m *TaskChunk) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChunkId != 0 {
		n += 1 + sovTaskPool(uint64(m.ChunkId))
	}
	l = len(m.DataHash)
	if l > 0 {
		n += 1 + l + sovTaskPool(uint64(l))
	}
	if m.ShardId != 0 {
		n += 1 + sovTaskPool(uint64(m.ShardId))
	}
	l = len(m.AssignedMiner)
	if l > 0 {
		n += 1 + l + sovTaskPool(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovTaskPool(uint64(l))
	}
	if m.ClaimedAt != 0 {
		n += 1 + sovTaskPool(uint64(m.ClaimedAt))
	}
	if m.CompletedAt != 0 {
		n += 1 + sovTaskPool(uint64(m.CompletedAt))
	}
	l = len(m.GradientHash)
	if l > 0 {
		n += 1 + l + sovTaskPool(uint64(l))
	}
	return n
}

func sovTaskPool(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTaskPool(x uint64) (n int) {
	return sovTaskPool(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TaskPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTaskPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaskPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaskPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTaskPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WindowId", wireType)
			}
			m.WindowId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTaskPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WindowId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalChunks", wireType)
			}
			m.TotalChunks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTaskPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalChunks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailableChunks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTaskPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTaskPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTaskPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AvailableChunks = append(m.AvailableChunks, TaskChunk{})
			if err := m.AvailableChunks[len(m.AvailableChunks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedChunks", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTaskPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTaskPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTaskPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CompletedChunks = append(m.CompletedChunks, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTaskPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTaskPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTaskPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedHeight", wireType)
			}
			m.CreatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTaskPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiryHeight", wireType)
			}
			m.ExpiryHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTaskPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiryHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTaskPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTaskPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TaskChunk) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTaskPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaskChunk: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaskChunk: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChunkId", wireType)
			}
			m.ChunkId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTaskPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChunkId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTaskPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTaskPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTaskPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardId", wireType)
			}
			m.ShardId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTaskPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssignedMiner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTaskPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTaskPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTaskPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssignedMiner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTaskPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTaskPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTaskPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimedAt", wireType)
			}
			m.ClaimedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTaskPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClaimedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedAt", wireType)
			}
			m.CompletedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTaskPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompletedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GradientHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTaskPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTaskPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTaskPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GradientHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTaskPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTaskPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTaskPool(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTaskPool
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTaskPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTaskPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTaskPool
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTaskPool
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTaskPool
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTaskPool        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTaskPool          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTaskPool = fmt.Errorf("proto: unexpected end of group")
)
