"""
Application constants and configuration values
"""

# Credit System
DEFAULT_CREDIT_COST = 1.0
CREDITS_PER_BLOCK = 100.0
MINIMUM_CREDIT_BALANCE = 0.0

# Rate Limiting
DEFAULT_CHAT_RATE_LIMIT = "10/minute"
DEFAULT_GET_RATE_LIMIT = "30/minute"
DEFAULT_POST_RATE_LIMIT = "20/minute"
HEALTH_CHECK_RATE_LIMIT = "100/minute"

# Timeouts (seconds)
DEFAULT_HTTP_CLIENT_TIMEOUT = 30.0
DEFAULT_DATABASE_TIMEOUT = 30.0
DEFAULT_SHUTDOWN_TIMEOUT = 30.0
DEFAULT_INFERENCE_TIMEOUT = 120.0

# Database Configuration
DEFAULT_DATABASE_CACHE_SIZE = -64000  # 64MB cache
DEFAULT_MAX_CONNECTIONS = 100
DEFAULT_CONNECTION_TIMEOUT = 30

# Network Configuration
DEFAULT_BACKEND_PORT = 8000
DEFAULT_PROMETHEUS_PORT = 9090
DEFAULT_REDIS_PORT = 6379

# Security
API_KEY_PREFIX = "r3mes_"
API_KEY_LENGTH = 32  # bytes, results in 64 hex chars
MAX_API_KEYS_PER_WALLET = 10

# Validation Limits
MAX_MESSAGE_LENGTH = 10000
MIN_MESSAGE_LENGTH = 1
MAX_WALLET_ADDRESS_LENGTH = 60
MIN_WALLET_ADDRESS_LENGTH = 20
MAX_API_KEY_NAME_LENGTH = 100

# Serving Nodes
DEFAULT_SERVING_NODE_MAX_AGE = 60  # seconds
DEFAULT_SERVING_NODE_CLEANUP_INTERVAL = 300  # 5 minutes

# Model Configuration
DEFAULT_MAX_WORKERS = 1
DEFAULT_SEMANTIC_ROUTER_THRESHOLD = 0.7

# Analytics Configuration
ANALYTICS_TIMELINE_MAX_POINTS = 100
ANALYTICS_HASHRATE_MULTIPLIER = 10.0
ANALYTICS_DEFAULT_GRANULARITY_DAYS = {
    "day": 1,
    "week": 7,
    "month": 30
}

# Monitoring
DEFAULT_METRICS_INTERVAL = 10.0  # seconds
DEFAULT_CACHE_TTL = 300  # 5 minutes

# CORS Configuration
DEFAULT_CORS_ORIGINS = "http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000"
CORS_MAX_AGE = 3600  # 1 hour

# Wallet Address Validation
WALLET_ADDRESS_PREFIX = "remes"
WALLET_ADDRESS_EXPECTED_LENGTH = 44  # remes1 + 38 characters

# Error Codes
ERROR_CODE_PREFIX = "R3MES_"

# File Paths
DEFAULT_DATABASE_PATH = "backend/database.db"
DEFAULT_CHAIN_JSON_PATH = "chain.json"
DEFAULT_CHECKPOINTS_DIR = "backend/checkpoints"